//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupportInformationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupportInformationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.zzNotTranslated.SupportInformationStrings", typeof(SupportInformationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSER.
        /// </summary>
        public static string BrowserInformationTitle {
            get {
                return ResourceManager.GetString("BrowserInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Folder.
        /// </summary>
        public static string CitaviAttachmentsPath {
            get {
                return ResourceManager.GetString("CitaviAttachmentsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Folder (Project Setting).
        /// </summary>
        public static string CitaviAttachmentsPathProjectSetting {
            get {
                return ResourceManager.GetString("CitaviAttachmentsPathProjectSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Folder (Resolved).
        /// </summary>
        public static string CitaviAttachmentsPathResolved {
            get {
                return ResourceManager.GetString("CitaviAttachmentsPathResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Folder.
        /// </summary>
        public static string CitaviBackupFolderPath {
            get {
                return ResourceManager.GetString("CitaviBackupFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Build Number.
        /// </summary>
        public static string CitaviBuildNumber {
            get {
                return ResourceManager.GetString("CitaviBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covers Folder (Resolved).
        /// </summary>
        public static string CitaviCoversPath {
            get {
                return ResourceManager.GetString("CitaviCoversPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITAVI FOLDERS.
        /// </summary>
        public static string CitaviFoldersTitle {
            get {
                return ResourceManager.GetString("CitaviFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITAVI.
        /// </summary>
        public static string CitaviInformationTitle {
            get {
                return ResourceManager.GetString("CitaviInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Installation Path.
        /// </summary>
        public static string CitaviInstallPath {
            get {
                return ResourceManager.GetString("CitaviInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Version.
        /// </summary>
        public static string CitaviIsPlaceholdersFeatureAllowed {
            get {
                return ResourceManager.GetString("CitaviIsPlaceholdersFeatureAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Licence.
        /// </summary>
        public static string CitaviLicence {
            get {
                return ResourceManager.GetString("CitaviLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CitaviProjectCategoriesCount {
            get {
                return ResourceManager.GetString("CitaviProjectCategoriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string CitaviProjectFilePath {
            get {
                return ResourceManager.GetString("CitaviProjectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string CitaviProjectKeywordsCount {
            get {
                return ResourceManager.GetString("CitaviProjectKeywordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string CitaviProjectReferencesCount {
            get {
                return ResourceManager.GetString("CitaviProjectReferencesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITAVI CURRENT PROJECT.
        /// </summary>
        public static string CitaviProjectTitle {
            get {
                return ResourceManager.GetString("CitaviProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Files Folder.
        /// </summary>
        public static string CitaviUserSettingsPath {
            get {
                return ResourceManager.GetString("CitaviUserSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Word Processor.
        /// </summary>
        public static string DefaultWordProcessor {
            get {
                return ResourceManager.GetString("DefaultWordProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT WORD PROCESSOR.
        /// </summary>
        public static string DefaultWordProcessorTitle {
            get {
                return ResourceManager.GetString("DefaultWordProcessorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox Version.
        /// </summary>
        public static string FirefoxVersion {
            get {
                return ResourceManager.GetString("FirefoxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Chrome Version.
        /// </summary>
        public static string GoogleChromeVersion {
            get {
                return ResourceManager.GetString("GoogleChromeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http 1.0.
        /// </summary>
        public static string Http10 {
            get {
                return ResourceManager.GetString("Http10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer Version.
        /// </summary>
        public static string InternetExplorerVersion {
            get {
                return ResourceManager.GetString("InternetExplorerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITAVI INTERNET CONNECTIVITY.
        /// </summary>
        public static string InternetInformationTitle {
            get {
                return ResourceManager.GetString("InternetInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Status.
        /// </summary>
        public static string NetworkInformation {
            get {
                return ResourceManager.GetString("NetworkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Antivirus Solution.
        /// </summary>
        public static string OSAntivirus {
            get {
                return ResourceManager.GetString("OSAntivirus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Number.
        /// </summary>
        public static string OSBuildNumber {
            get {
                return ResourceManager.GetString("OSBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Current Language.
        /// </summary>
        public static string OSCurrentLanguage {
            get {
                return ResourceManager.GetString("OSCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Current UI Language.
        /// </summary>
        public static string OSCurrentUILanguage {
            get {
                return ResourceManager.GetString("OSCurrentUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OSCurrentVersion {
            get {
                return ResourceManager.GetString("OSCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string OSEdition {
            get {
                return ResourceManager.GetString("OSEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Language.
        /// </summary>
        public static string OSInstallLanguage {
            get {
                return ResourceManager.GetString("OSInstallLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64bit Operating System.
        /// </summary>
        public static string OSIs64bit {
            get {
                return ResourceManager.GetString("OSIs64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Version.
        /// </summary>
        public static string OSMajorVersion {
            get {
                return ResourceManager.GetString("OSMajorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Version.
        /// </summary>
        public static string OSMinorVersion {
            get {
                return ResourceManager.GetString("OSMinorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string OSProductName {
            get {
                return ResourceManager.GetString("OSProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release ID.
        /// </summary>
        public static string OSReleaseId {
            get {
                return ResourceManager.GetString("OSReleaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Root Path.
        /// </summary>
        public static string OSSystemRoot {
            get {
                return ResourceManager.GetString("OSSystemRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Version.
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Support-Infos {0}.
        /// </summary>
        public static string SupportInfoFileName {
            get {
                return ResourceManager.GetString("SupportInfoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM.
        /// </summary>
        public static string SystemInformationTitle {
            get {
                return ResourceManager.GetString("SystemInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string WebProxy {
            get {
                return ResourceManager.GetString("WebProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webservice Check.
        /// </summary>
        public static string WebserviceCheck {
            get {
                return ResourceManager.GetString("WebserviceCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows SID.
        /// </summary>
        public static string WindowsSID {
            get {
                return ResourceManager.GetString("WindowsSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Add-Ins.
        /// </summary>
        public static string WinwordAddinsDisabledList {
            get {
                return ResourceManager.GetString("WinwordAddinsDisabledList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICROSOFT WORD ADD-INS.
        /// </summary>
        public static string WinwordAddinsInformationTitle {
            get {
                return ResourceManager.GetString("WinwordAddinsInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Installed Add-Ins.
        /// </summary>
        public static string WinwordAddinsList {
            get {
                return ResourceManager.GetString("WinwordAddinsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word installed from Microsoft Store.
        /// </summary>
        public static string WinwordAppstore {
            get {
                return ResourceManager.GetString("WinwordAppstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitness.
        /// </summary>
        public static string WinwordBitness {
            get {
                return ResourceManager.GetString("WinwordBitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Build Number.
        /// </summary>
        public static string WinwordBuildNumber {
            get {
                return ResourceManager.GetString("WinwordBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Compatibilty Mode.
        /// </summary>
        public static string WinwordCompatibilityMode {
            get {
                return ResourceManager.GetString("WinwordCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Document Format.
        /// </summary>
        public static string WinwordDocumentFormat {
            get {
                return ResourceManager.GetString("WinwordDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICROSOFT WORD.
        /// </summary>
        public static string WinwordInformationTitle {
            get {
                return ResourceManager.GetString("WinwordInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        public static string WinwordInterfaceLanguage {
            get {
                return ResourceManager.GetString("WinwordInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Path (Version from Registry).
        /// </summary>
        public static string WinwordPathCurVer {
            get {
                return ResourceManager.GetString("WinwordPathCurVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Path (Version from Instance).
        /// </summary>
        public static string WinwordPathInstance {
            get {
                return ResourceManager.GetString("WinwordPathInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Document Default Format.
        /// </summary>
        public static string WinwordSaveFormat {
            get {
                return ResourceManager.GetString("WinwordSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust Center Settings.
        /// </summary>
        public static string WinwordTrustcenterSettings {
            get {
                return ResourceManager.GetString("WinwordTrustcenterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trusted locations are disabled?.
        /// </summary>
        public static string WinwordTrustedLocationDisabled {
            get {
                return ResourceManager.GetString("WinwordTrustedLocationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Trusted Locations.
        /// </summary>
        public static string WinwordTrustedLocationList {
            get {
                return ResourceManager.GetString("WinwordTrustedLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network paths are allowed?.
        /// </summary>
        public static string WinwordTrustedLocationNetwork {
            get {
                return ResourceManager.GetString("WinwordTrustedLocationNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Locations.
        /// </summary>
        public static string WinwordTrustedLocationSettings {
            get {
                return ResourceManager.GetString("WinwordTrustedLocationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBA Installation.
        /// </summary>
        public static string WinwordVBAInfo {
            get {
                return ResourceManager.GetString("WinwordVBAInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Version according to Registry.
        /// </summary>
        public static string WinwordVersionCurVer {
            get {
                return ResourceManager.GetString("WinwordVersionCurVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Version according to Word.
        /// </summary>
        public static string WinwordVersionInstance {
            get {
                return ResourceManager.GetString("WinwordVersionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Add-In Files.
        /// </summary>
        public static string WordAddInFilesList {
            get {
                return ResourceManager.GetString("WordAddInFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Add-In LoadBehavior Settings.
        /// </summary>
        public static string WordAddInLoadBehavior {
            get {
                return ResourceManager.GetString("WordAddInLoadBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAI.
        /// </summary>
        public static string WordAddInTitle {
            get {
                return ResourceManager.GetString("WordAddInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Add-In Version.
        /// </summary>
        public static string WordAddInVersion {
            get {
                return ResourceManager.GetString("WordAddInVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Version.
        /// </summary>
        public static string WordVersion {
            get {
                return ResourceManager.GetString("WordVersion", resourceCulture);
            }
        }
    }
}
