//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRM() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.CRM", typeof(CRM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swiss Academic Software GmbH - Florhofstrasse 2 - 8820 Waedenswil - Switzerland ähnelt.
        /// </summary>
        public static string CRM_Email_address {
            get {
                return ResourceManager.GetString("CRM_Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in to account now ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your university or organization recently renewed its site license. The new license key can now be found in your account. Log in to your account to verify that you are still affiliated with the university or organization.
        ///
        ///Your license is valid for ##productname. Do you need a license for an earlier Citavi version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Citavi site license was renewed ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The site license that you purchased for your employees and students has been renewed. All Citavi users will receive an email informing them of the next steps to take. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi 6 users have to confirm that they are still members of your organization. Depending on your chosen settings, this can be accomplished by (a) clicking the confirmation link in the email; (b) logging in to Shibboleth; (c) entering a voucher code. No license information is copied and then entered in Citavi.
        ///##newline
        ///Citavi 5 users have to log in to their Citavi accounts. There, the license key can be found and must be copied to the Clipboard. It can then be entered in Citavi 5. Users can also request [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information for administrators: Your Citavi site license was renewed ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn more in the Citavi Manual ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your university is using a site license for Citavi. To create a settings file, which among other things can include login credentials to restricted databases, you need a special license key file. Attached you will find this special license key file. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To learn more about creating settings files, please see the Citavi Manual. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License key for Citavi settings file export for ##organization ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to the manual  ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your university currently has a site license for Citavi. To use Citavi on public computers, such as in a library or computer lab, you can use the attached license key file for  ##productname to simplify deployment. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Citavi Manual describes how to use the file. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi License Key File for Public Workstations for  ##organization ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in to account ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your university or organization recently renewed its site license. In September 2016 we changed how you can get your license information. The new license key can now be found in your account. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you don&apos;t have a Citavi Account yet, you can create one below. You&apos;ll be led through the process step by step. If you already have a Citavi Account, click the link to log in.
        ///##newline
        ///Your license is valid for ##productname. Do you need a license for an earlier Citavi version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Citavi site license has been renewed ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a password ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your university or organization recently renewed its site license for Citavi. In September 2016 we changed our licensing procedure. You can now find your new license key in your Citavi account. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To complete your Citavi account registration, choose a password for logging in to your account.
        ///##newline
        ///Your license is valid for ##productname. Do you need a license for an earlier Citavi version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Citavi site license has been renewed ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in to account ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Citavi site license has been renewed. You can find the new license key in your Citavi account. Log in to access the license key.
        ///##newline
        ///Your license is valid for ##productname. Do you need a license for an earlier Citavi version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Citavi site license has been renewed ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you did not make this request, please ignore this message. ähnelt.
        /// </summary>
        public static string CRM_Email_disclaimer {
            get {
                return ResourceManager.GetString("CRM_Email_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p/&gt; ähnelt.
        /// </summary>
        public static string CRM_Email_newline {
            get {
                return ResourceManager.GetString("CRM_Email_newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Best regards, ähnelt.
        /// </summary>
        public static string CRM_Email_regards_firstline {
            get {
                return ResourceManager.GetString("CRM_Email_regards_firstline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Citavi Team ähnelt.
        /// </summary>
        public static string CRM_Email_regards_secondline {
            get {
                return ResourceManager.GetString("CRM_Email_regards_secondline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dear {0}, ähnelt.
        /// </summary>
        public static string CRM_Email_Salutation {
            get {
                return ResourceManager.GetString("CRM_Email_Salutation", resourceCulture);
            }
        }
    }
}
