//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CRMde {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMde() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.CRMde", typeof(CRMde).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swiss Academic Software GmbH - Florhofstrasse 2 - 8820 Wädenswil - Schweiz ähnelt.
        /// </summary>
        public static string CRM_Email_address {
            get {
                return ResourceManager.GetString("CRM_Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Account ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule oder Organisation hat die Campuslizenz verlängert. Die neuen Lizenzdaten stehen in Ihrem Citavi-Account bereit. Melden Sie sich an, um sie abzurufen.
        ///##newline
        ///Ihre Lizenz ist gültig für ##productname. Benötigen Sie eine Lizenz für eine ältere Citavi-Version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Citavi-Campuslizenz wurde verlängert ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtension_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtension_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Ihrer Hochschule bieten Sie eine Citavi-Campuslizenz an. Der Lizenzvertrag wurde jetzt verlängert. Alle Citavi-Nutzerinnen und -Nutzer erhalten eine E-Mail, in der sie über die nächsten Schritte informiert werden. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wer Citavi 6 nutzt, muss bestätigen, dass er noch Mitglied Ihrer Hochschule ist. Abhängig von Ihren Einstellungen geschieht das über einen der folgenden Wege: Klick auf den Verifizierungs-Link in der E-Mail oder Shibboleth-Anmeldung oder Eingabe eines neuen Gutscheins. (Es müssen keine Lizenzdaten kopiert und in Citavi eingegeben werden.)
        ///##newline
        ///Wer Citavi 5 nutzt, muss sich in seinem Citavi Account anmelden. Die Lizenzdaten müssen aus dem Account kopiert und in Citavi 5 eingegeben werden. Wer eine noc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrativer Hinweis: Ihre Campuslizenz wurde verlängert ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionInfoMail_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionInfoMail_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handbuch-Artikel aufrufen ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule nutzt eine Campuslizenz unserer Software »Citavi – Wissen organisieren«. Damit Sie aus Citavi heraus eine Einstellungsdatei erstellen können, die u.a. die Zugangsdaten zu den lizenzpflichtigen Fachdatenbanken enthält, benötigen Sie eine Speziallizenz, die wir Ihnen in der Anlage senden. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Handbuch erläutern wir die Verwendung der Datei. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenz für Export einer Einstellungsdatei für ##organization ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfileExportData_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfileExportData_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Handbuch-Artikel aufrufen ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule nutzt eine Campuslizenz unserer Software »Citavi – Wissen organisieren«. Damit Sie Citavi auch auf öffentlichen Rechnern (z.B. in einem Schulungsraum) nutzen können, senden wir Ihnen beiliegend eine Lizenzdatei für  ##productname zu. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im Handbuch erläutern wir die Verwendung der Datei. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lizenzdatei für öffentliche PCs für ##organization ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLicensfilePublicInstall_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLicensfilePublicInstall_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Account ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule oder Organisation hat die Campuslizenz verlängert. Wir haben das Verfahren, mit dem Sie die Lizenzdaten erhalten, im September 2016 geändert und Ihre Lizenzdaten in Ihrem Account bereitgestellt.
        /// ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn Sie noch keinen Citavi Account haben, können Sie ihn im Folgenden einrichten. Sie werden Schritt für Schritt durch den Prozess geführt. Wenn Sie schon einen Citavi Account haben, führt Sie der Link zur Anmeldung.
        ///##newline
        ///Ihre Lizenz ist gültig für ##productname. Benötigen Sie eine Lizenz für eine ältere Citavi-Version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Citavi-Campuslizenz wurde verlängert ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionLoginShibboleth_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionLoginShibboleth_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort wählen ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule oder Organisation hat die Campuslizenz verlängert. Wir haben das Verfahren, mit dem Sie die Lizenzdaten erhalten, im September 2016 geändert und Ihre Lizenzdaten in Ihrem Account bereitgestellt. ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Um Ihren Citavi-Account erfolgreich einzurichten, fehlt nur noch ein Schritt: Wählen Sie ein Passwort, mit dem Sie sich zukünftig an Ihrem Account anmelden.
        ///##newline
        ///Ihre Lizenz ist gültig für ##productname. Benötigen Sie eine Lizenz für eine ältere Citavi-Version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_second_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_second_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Citavi-Campuslizenz wurde verlängert ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyAccount_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyAccount_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Account ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_button {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Hochschule oder Organisation hat die Campuslizenz verlängert. Die neuen Lizenzdaten stehen in Ihrem Citavi-Account bereit. Melden Sie sich an, um sie abzurufen.
        ///##newline
        ///Ihre Lizenz ist gültig für ##productname. Benötigen Sie eine Lizenz für eine ältere Citavi-Version? ##helpgetoldversion
        ///
        ///##addOn ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_first_paragraph {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_first_paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Citavi-Campuslizenz wurde verlängert ähnelt.
        /// </summary>
        public static string CRM_Email_CampusContractExtensionVerifyLicense_subject {
            get {
                return ResourceManager.GetString("CRM_Email_CampusContractExtensionVerifyLicense_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn Sie diese Anforderung nicht veranlasst haben, ignorieren Sie bitte diese E-Mail. ähnelt.
        /// </summary>
        public static string CRM_Email_disclaimer {
            get {
                return ResourceManager.GetString("CRM_Email_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;p/&gt; ähnelt.
        /// </summary>
        public static string CRM_Email_newline {
            get {
                return ResourceManager.GetString("CRM_Email_newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mit freundlichen Grüßen ähnelt.
        /// </summary>
        public static string CRM_Email_regards_firstline {
            get {
                return ResourceManager.GetString("CRM_Email_regards_firstline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Citavi-Team ähnelt.
        /// </summary>
        public static string CRM_Email_regards_secondline {
            get {
                return ResourceManager.GetString("CRM_Email_regards_secondline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo {0}, ähnelt.
        /// </summary>
        public static string CRM_Email_Salutation {
            get {
                return ResourceManager.GetString("CRM_Email_Salutation", resourceCulture);
            }
        }
    }
}
