//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileDialogFilters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileDialogFilters() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.FileDialogFilters", typeof(FileDialogFilters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Access Databases  (*.mdb)|*.mdb|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word Document (*.docx)|*.docx|Word 97-2003 Document (*.doc)|*.doc|PDF (*.pdf)|*.pdf|OpenDocument Text (*.odt)|*.odt|Rich Text Format (*.rtf)|*.rtf|Webpage (*.html)|*.html|XPS (*.xps)|*.xps|Plain Text (*.txt)|*.txt ähnelt.
        /// </summary>
        public static string AsposeDocumentSave {
            get {
                return ResourceManager.GetString("AsposeDocumentSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bibliographix Files (*.bgx; *bx7; *bx9)|*.bgx;*bx7;*bx9|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Bibliographix {
            get {
                return ResourceManager.GetString("Bibliographix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groupings (*.ctvbgd)|*.ctvbgd ähnelt.
        /// </summary>
        public static string BibliographyGroupingSets_Export {
            get {
                return ResourceManager.GetString("BibliographyGroupingSets_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groupings (*.ctvbgd)|*.ctvbgd|All Files|*.* ähnelt.
        /// </summary>
        public static string BibliographyGroupingSets_Import {
            get {
                return ResourceManager.GetString("BibliographyGroupingSets_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BibTeX Files (*.bib; *.txt)|*.bib;*.txt|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string BibTeX {
            get {
                return ResourceManager.GetString("BibTeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Bitmap Formats (*.bmp; *.gif; *.ico; *.jpg; *.jpeg; *.png; *.tif; *.tiff)|*.bmp; *.gif; *.ico; *.jpg; *.jpeg; *.png; *.tif; *.tiff|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Bitmap {
            get {
                return ResourceManager.GetString("Bitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JPEG |*.jpg|BMP |*.bmp|GIF |*.gif|PNG |*.png|TIFF |*.tif ähnelt.
        /// </summary>
        public static string BitmapSave {
            get {
                return ResourceManager.GetString("BitmapSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenDocument Spreadsheets (*.ods)|*.ods|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Calc {
            get {
                return ResourceManager.GetString("Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ods ähnelt.
        /// </summary>
        public static string CalcExtension {
            get {
                return ResourceManager.GetString("CalcExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ccs ähnelt.
        /// </summary>
        public static string CitationStyleExtension {
            get {
                return ResourceManager.GetString("CitationStyleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Projects|*.ctv6;*.ctvdbs6;*.ctv6archive;*.ctv6bak;*.ctv5;*.ctvdbs5;*.ctv4;*.ctt4;*.ctv3;*.ctt3|All Files|*.* ähnelt.
        /// </summary>
        public static string Citavi {
            get {
                return ResourceManager.GetString("Citavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Projects|*.ctv5;*.ctvdbs5 ähnelt.
        /// </summary>
        public static string Citavi5 {
            get {
                return ResourceManager.GetString("Citavi5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Projects|*.ctv6;*.ctvdbs6 ähnelt.
        /// </summary>
        public static string Citavi6 {
            get {
                return ResourceManager.GetString("Citavi6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Archive|*.ctv6archive ähnelt.
        /// </summary>
        public static string Citavi6Archive {
            get {
                return ResourceManager.GetString("Citavi6Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ctv6archive ähnelt.
        /// </summary>
        public static string CitaviArchiveExtension {
            get {
                return ResourceManager.GetString("CitaviArchiveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ctv6bak ähnelt.
        /// </summary>
        public static string CitaviBackupExtension {
            get {
                return ResourceManager.GetString("CitaviBackupExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ctc ähnelt.
        /// </summary>
        public static string CitaviCacheExtension {
            get {
                return ResourceManager.GetString("CitaviCacheExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Citation Style (*.ccs)|*.ccs|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string CitaviCitationStyle {
            get {
                return ResourceManager.GetString("CitaviCitationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ctvdbs6 ähnelt.
        /// </summary>
        public static string CitaviDBServerConnectionFileExtension {
            get {
                return ResourceManager.GetString("CitaviDBServerConnectionFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi DBServer Databases|*.cdm6 ähnelt.
        /// </summary>
        public static string CitaviDBServerDatabase {
            get {
                return ResourceManager.GetString("CitaviDBServerDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi DBServer Licenses (*.cdb6lic)|*.cdb6lic|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string CitaviDBServerLicense {
            get {
                return ResourceManager.GetString("CitaviDBServerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi DBServer Projects|*.ctvdbs6 ähnelt.
        /// </summary>
        public static string CitaviDBServerProject {
            get {
                return ResourceManager.GetString("CitaviDBServerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ctv6 ähnelt.
        /// </summary>
        public static string CitaviDefaultExtension {
            get {
                return ResourceManager.GetString("CitaviDefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Activity Log (*.zip)|*.zip ähnelt.
        /// </summary>
        public static string CitaviLog {
            get {
                return ResourceManager.GetString("CitaviLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Settings Files (*.csd;*.xml)|*.csd;*.xml|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string CitaviSettings {
            get {
                return ResourceManager.GetString("CitaviSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cover Art Formats|*.bmp; *.emf; *.exif; *.gif; *.ico; *.jpg; *.jpeg; *.pdf; *.png; *.tif; *.tiff; *.wmf|All files|*.* ähnelt.
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV Files (*.csv)|*.csv|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Csv {
            get {
                return ResourceManager.GetString("Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EndNote Libraries (*.enl)|*.enl|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string EndNote {
            get {
                return ResourceManager.GetString("EndNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel Workbooks (*.xlsx)|*.xlsx|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel 97-2003 Workbook (*.xls)|*.xls ähnelt.
        /// </summary>
        public static string Excel2003Save {
            get {
                return ResourceManager.GetString("Excel2003Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .xls ähnelt.
        /// </summary>
        public static string ExcelExtension {
            get {
                return ResourceManager.GetString("ExcelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Image Formats (*.bmp; *.emf; *.exif; *.gif; *.ico; *.jpg; *.jpeg; *.png; *.tif; *.tiff; *.wmf)|*.bmp; *.emf; *.exif; *.gif; *.ico; *.jpg; *.jpeg; *.png; *.tif; *.tiff; *.wmf|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LiteRat Databases (*.mdb)|*.mdb|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string LiteRat {
            get {
                return ResourceManager.GetString("LiteRat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mind Manager Documents  (*.mmap)|*.mmap|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string MindManager {
            get {
                return ResourceManager.GetString("MindManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MPX File (*.mpx)|*.mpx|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string MPX {
            get {
                return ResourceManager.GetString("MPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Files (*.pdf)|*.pdf|All Files|*.* ähnelt.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supported Formats (*.rtf; *.txt; *.doc; *.docx; *.odt;*.pdf;*.csv)|*.txt;*.rtf;*.doc;*.docx;*.odt;*.pdf;*.csv|Rich Text Format (*.rtf)|*.rtf|ASCII Text (*.txt; *.csv)|*.txt;*.csv|Unicode Text (*.txt)|*.txt|Word Documents (*.doc; *.docx)|*.doc;*.docx|OpenDocument Text (*.odt)|*.odt|PDF (*.pdf)|*.pdf|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string ReferenceIdentifierLookup {
            get {
                return ResourceManager.GetString("ReferenceIdentifierLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RIS Files, Text Files (*.ris; *.txt)|*.ris;*.txt|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Ris {
            get {
                return ResourceManager.GetString("Ris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text files (*.txt)|*.txt|html files (*.html)|*.html ähnelt.
        /// </summary>
        public static string SaveChatHistoryFilter {
            get {
                return ResourceManager.GetString("SaveChatHistoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQLite Databases (*.sqlite)|*.sqlite|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string SQLite {
            get {
                return ResourceManager.GetString("SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Files (*.txt; *.csv)|*.txt; *csv|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string TabularText {
            get {
                return ResourceManager.GetString("TabularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TeX Documents (*.tex)|*.tex|LyX Documents (*.lyx)|*.lyx|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string TeXFilter {
            get {
                return ResourceManager.GetString("TeXFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Files (*.txt)|*.txt|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Txt {
            get {
                return ResourceManager.GetString("Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word Documents  (*.doc; *.docx)|*.doc;*.docx|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supported Formats (*.rtf; *.txt; *.doc; *.docx; *.odt)|*.txt;*.rtf;*.doc;*.docx;*.odt|Rich Text Format (*.rtf)|*.rtf|ASCII Text (*.txt)|*.txt|Unicode Text (*.txt)|*.txt|Word Documents (*.doc; *.docx)|*.doc;*.docx|OpenDocument Text (*.odt)|*.odt|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string WordProcessorOpen {
            get {
                return ResourceManager.GetString("WordProcessorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rich Text Format|*.rtf|Plain Text|*.txt|Word Document (*.doc)|*.doc|OpenDocument Text (*.odt)|*.odt ähnelt.
        /// </summary>
        public static string WordProcessorSave {
            get {
                return ResourceManager.GetString("WordProcessorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenDocument Text (*.odt)|*.odt ähnelt.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Xml Files (*.xml)|*.xml|All Files (*.*)|*.* ähnelt.
        /// </summary>
        public static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
    }
}
