//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormTexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.FormTexts", typeof(FormTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About Citavi ähnelt.
        /// </summary>
        public static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More Fields ähnelt.
        /// </summary>
        public static string AdditionalFieldsForm {
            get {
                return ResourceManager.GetString("AdditionalFieldsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Add-Ons ähnelt.
        /// </summary>
        public static string AddOnsForm {
            get {
                return ResourceManager.GetString("AddOnsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Keywords ähnelt.
        /// </summary>
        public static string ApplyKeywordsForm {
            get {
                return ResourceManager.GetString("ApplyKeywordsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign Categories ähnelt.
        /// </summary>
        public static string AssignCategoriesForm {
            get {
                return ResourceManager.GetString("AssignCategoriesForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background task error ähnelt.
        /// </summary>
        public static string BackgroundTaskErrorDialog {
            get {
                return ResourceManager.GetString("BackgroundTaskErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groupings from the Citavi Server ähnelt.
        /// </summary>
        public static string BackOfficeCitationStyleElementsDialog_BibliographyGroupingSet {
            get {
                return ResourceManager.GetString("BackOfficeCitationStyleElementsDialog_BibliographyGroupingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder for Backups ähnelt.
        /// </summary>
        public static string BackupFolderPathDialog {
            get {
                return ResourceManager.GetString("BackupFolderPathDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Add Tasks ähnelt.
        /// </summary>
        public static string BatchAddTasksDialog {
            get {
                return ResourceManager.GetString("BatchAddTasksDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Assign Groups ähnelt.
        /// </summary>
        public static string BatchApplyOrRemoveGroupsDialog_Apply {
            get {
                return ResourceManager.GetString("BatchApplyOrRemoveGroupsDialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Remove Groups ähnelt.
        /// </summary>
        public static string BatchApplyOrRemoveGroupsDialog_Remove {
            get {
                return ResourceManager.GetString("BatchApplyOrRemoveGroupsDialog_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Apply Keywords ähnelt.
        /// </summary>
        public static string BatchApplyOrRemoveKeywordsDialog_Apply {
            get {
                return ResourceManager.GetString("BatchApplyOrRemoveKeywordsDialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Remove Keywords ähnelt.
        /// </summary>
        public static string BatchApplyOrRemoveKeywordsDialog_Remove {
            get {
                return ResourceManager.GetString("BatchApplyOrRemoveKeywordsDialog_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Assign Categories ähnelt.
        /// </summary>
        public static string BatchAssignOrRemoveCategoriesDialog_Assign {
            get {
                return ResourceManager.GetString("BatchAssignOrRemoveCategoriesDialog_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Remove Categories ähnelt.
        /// </summary>
        public static string BatchAssignOrRemoveCategoriesDialog_Remove {
            get {
                return ResourceManager.GetString("BatchAssignOrRemoveCategoriesDialog_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize Overview ähnelt.
        /// </summary>
        public static string BibliographyCompositionEditorForm {
            get {
                return ResourceManager.GetString("BibliographyCompositionEditorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppiertes Literaturverzeichnis ähnelt.
        /// </summary>
        public static string BibliographyGroupingDialog {
            get {
                return ResourceManager.GetString("BibliographyGroupingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouping Section ähnelt.
        /// </summary>
        public static string BibliographyGroupingForm {
            get {
                return ResourceManager.GetString("BibliographyGroupingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group Bibliography ähnelt.
        /// </summary>
        public static string BibliographyGroupingSetsForm {
            get {
                return ResourceManager.GetString("BibliographyGroupingSetsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export BibTeX File ähnelt.
        /// </summary>
        public static string BibTeXExport_1 {
            get {
                return ResourceManager.GetString("BibTeXExport_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize BibTeX Export: {0} ähnelt.
        /// </summary>
        public static string BibTeXExport_2 {
            get {
                return ResourceManager.GetString("BibTeXExport_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize BibTeX Export: {0} (Copy) ähnelt.
        /// </summary>
        public static string BibTeXExport_2_Copy {
            get {
                return ResourceManager.GetString("BibTeXExport_2_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize BibTeX Keys ähnelt.
        /// </summary>
        public static string BibTeXKeyDialog {
            get {
                return ResourceManager.GetString("BibTeXKeyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Booksellers ähnelt.
        /// </summary>
        public static string BookOrderForm {
            get {
                return ResourceManager.GetString("BookOrderForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Booksellers ähnelt.
        /// </summary>
        public static string BookStoreFavoritesDialog {
            get {
                return ResourceManager.GetString("BookStoreFavoritesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string CategoryForm {
            get {
                return ResourceManager.GetString("CategoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Character Format ähnelt.
        /// </summary>
        public static string CharacterFormatDialog {
            get {
                return ResourceManager.GetString("CharacterFormatDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Reference ähnelt.
        /// </summary>
        public static string ChooseReferenceDialog {
            get {
                return ResourceManager.GetString("ChooseReferenceDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citation Key ähnelt.
        /// </summary>
        public static string CitationKeyDialog {
            get {
                return ResourceManager.GetString("CitationKeyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Citation Style ähnelt.
        /// </summary>
        public static string CitationStyleEditorInitialDialog {
            get {
                return ResourceManager.GetString("CitationStyleEditorInitialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Citation Styles ähnelt.
        /// </summary>
        public static string CitationStyleFavoriteDialog {
            get {
                return ResourceManager.GetString("CitationStyleFavoriteDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse Citation Styles ähnelt.
        /// </summary>
        public static string CitationStyleForm {
            get {
                return ResourceManager.GetString("CitationStyleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citation Styles on www.citavi.com ähnelt.
        /// </summary>
        public static string CitationStyleListDialog {
            get {
                return ResourceManager.GetString("CitationStyleListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citation Style Properties ähnelt.
        /// </summary>
        public static string CitationStyleSettingsDialog {
            get {
                return ResourceManager.GetString("CitationStyleSettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string CitaviTextMessageBox {
            get {
                return ResourceManager.GetString("CitaviTextMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change project role ähnelt.
        /// </summary>
        public static string CloudChangeProjectRoleDialog {
            get {
                return ResourceManager.GetString("CloudChangeProjectRoleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share project ähnelt.
        /// </summary>
        public static string CloudProjectMembersDialog {
            get {
                return ResourceManager.GetString("CloudProjectMembersDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column Information ähnelt.
        /// </summary>
        public static string ColumnInformationDialog {
            get {
                return ResourceManager.GetString("ColumnInformationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit component ähnelt.
        /// </summary>
        public static string ComponentPartEditorForm {
            get {
                return ResourceManager.GetString("ComponentPartEditorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert Project ähnelt.
        /// </summary>
        public static string ConvertProjectsDialog {
            get {
                return ResourceManager.GetString("ConvertProjectsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy or Move to a Citavi Project ähnelt.
        /// </summary>
        public static string CopyOrMoveToProjectWizard {
            get {
                return ResourceManager.GetString("CopyOrMoveToProjectWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Correct Paths ähnelt.
        /// </summary>
        public static string CorrectPathsDialog {
            get {
                return ResourceManager.GetString("CorrectPathsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Annotated Project Bibliography ähnelt.
        /// </summary>
        public static string CreateBibliographyDialog {
            get {
                return ResourceManager.GetString("CreateBibliographyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options for Group Headers ähnelt.
        /// </summary>
        public static string CreateBibliographyOptionsDialog {
            get {
                return ResourceManager.GetString("CreateBibliographyOptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compilation ähnelt.
        /// </summary>
        public static string CreateCompilationDialog {
            get {
                return ResourceManager.GetString("CreateCompilationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created or modified by ähnelt.
        /// </summary>
        public static string CreatedByModifiedByForm {
            get {
                return ResourceManager.GetString("CreatedByModifiedByForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grouped Project Bibliography ähnelt.
        /// </summary>
        public static string CreateGroupedBibliographyDialog {
            get {
                return ResourceManager.GetString("CreateGroupedBibliographyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project ähnelt.
        /// </summary>
        public static string CreateProjectDialogEx {
            get {
                return ResourceManager.GetString("CreateProjectDialogEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task List ähnelt.
        /// </summary>
        public static string CreateTaskListDialog {
            get {
                return ResourceManager.GetString("CreateTaskListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Field ähnelt.
        /// </summary>
        public static string CustomFieldDialog {
            get {
                return ResourceManager.GetString("CustomFieldDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select your favorite quotation types ähnelt.
        /// </summary>
        public static string CustomizeReferenceQuotationsTBMDialog {
            get {
                return ResourceManager.GetString("CustomizeReferenceQuotationsTBMDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Export Presets ähnelt.
        /// </summary>
        public static string DataExchangePropertyConfigurationDialog_Export {
            get {
                return ResourceManager.GetString("DataExchangePropertyConfigurationDialog_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Saved Searches ähnelt.
        /// </summary>
        public static string DataExchangePropertyConfigurationDialog_OnlineImport {
            get {
                return ResourceManager.GetString("DataExchangePropertyConfigurationDialog_OnlineImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Date Format ähnelt.
        /// </summary>
        public static string DateTimeFormatDialog {
            get {
                return ResourceManager.GetString("DateTimeFormatDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Unused Items ähnelt.
        /// </summary>
        public static string DeleteUnusedItemsDialog {
            get {
                return ResourceManager.GetString("DeleteUnusedItemsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct Import ähnelt.
        /// </summary>
        public static string DirectImportDialog {
            get {
                return ResourceManager.GetString("DirectImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Link ähnelt.
        /// </summary>
        public static string EntityLinkForm {
            get {
                return ResourceManager.GetString("EntityLinkForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equivalent Characters ähnelt.
        /// </summary>
        public static string EquivalentCharactersListDialog {
            get {
                return ResourceManager.GetString("EquivalentCharactersListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equivalent Characters ähnelt.
        /// </summary>
        public static string EquivalentCharactersPairDialog {
            get {
                return ResourceManager.GetString("EquivalentCharactersPairDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrative Settings Assistant ähnelt.
        /// </summary>
        public static string ExportAdminSettingsDialog {
            get {
                return ResourceManager.GetString("ExportAdminSettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        public static string ExportWizardDialog {
            get {
                return ResourceManager.GetString("ExportWizardDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced Search ähnelt.
        /// </summary>
        public static string ExtendedSearchForm {
            get {
                return ResourceManager.GetString("ExtendedSearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter by Field Content ähnelt.
        /// </summary>
        public static string FilterDialog {
            get {
                return ResourceManager.GetString("FilterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Subscribed Databases ähnelt.
        /// </summary>
        public static string FindLicensedDatabasesDialog {
            get {
                return ResourceManager.GetString("FindLicensedDatabasesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        public static string FolderForm {
            get {
                return ResourceManager.GetString("FolderForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} - {1} (Read Only) - {2} ähnelt.
        /// </summary>
        public static string FormTextReadOnly {
            get {
                return ResourceManager.GetString("FormTextReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} - {1} (Read Only) ähnelt.
        /// </summary>
        public static string FormTextSimpleReadOnly {
            get {
                return ResourceManager.GetString("FormTextSimpleReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repairing database… ähnelt.
        /// </summary>
        public static string GenericProgressDialog_RepairProject {
            get {
                return ResourceManager.GetString("GenericProgressDialog_RepairProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string GroupForm {
            get {
                return ResourceManager.GetString("GroupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups ähnelt.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About This Quick Help Text ähnelt.
        /// </summary>
        public static string HelpInformationForm {
            get {
                return ResourceManager.GetString("HelpInformationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cover Art ähnelt.
        /// </summary>
        public static string ImageForm {
            get {
                return ResourceManager.GetString("ImageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string ImportForm {
            get {
                return ResourceManager.GetString("ImportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string ImportWizardDialog {
            get {
                return ResourceManager.GetString("ImportWizardDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Table ähnelt.
        /// </summary>
        public static string InsertTableDialog {
            get {
                return ResourceManager.GetString("InsertTableDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize BibTeX Key Template ähnelt.
        /// </summary>
        public static string KeyConfiguration_BibTeXKey {
            get {
                return ResourceManager.GetString("KeyConfiguration_BibTeXKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customize Citation Key Template ähnelt.
        /// </summary>
        public static string KeyConfiguration_CitationKey {
            get {
                return ResourceManager.GetString("KeyConfiguration_CitationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BibTeX Key Settings ähnelt.
        /// </summary>
        public static string KeyConfigurationDialog {
            get {
                return ResourceManager.GetString("KeyConfigurationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Character ähnelt.
        /// </summary>
        public static string KeyReplacementInputDialog {
            get {
                return ResourceManager.GetString("KeyReplacementInputDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keyword ähnelt.
        /// </summary>
        public static string KeywordForm {
            get {
                return ResourceManager.GetString("KeywordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keywords ähnelt.
        /// </summary>
        public static string KeywordList {
            get {
                return ResourceManager.GetString("KeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quotation ähnelt.
        /// </summary>
        public static string KnowledgeItemFileForm {
            get {
                return ResourceManager.GetString("KnowledgeItemFileForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thought ähnelt.
        /// </summary>
        public static string KnowledgeItemFileForm_Thought {
            get {
                return ResourceManager.GetString("KnowledgeItemFileForm_Thought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quotation ähnelt.
        /// </summary>
        public static string KnowledgeItemTextForm {
            get {
                return ResourceManager.GetString("KnowledgeItemTextForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thought ähnelt.
        /// </summary>
        public static string KnowledgeItemTextForm_Thought {
            get {
                return ResourceManager.GetString("KnowledgeItemTextForm_Thought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Library ähnelt.
        /// </summary>
        public static string LibraryForm {
            get {
                return ResourceManager.GetString("LibraryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Libraries ähnelt.
        /// </summary>
        public static string LibraryList {
            get {
                return ResourceManager.GetString("LibraryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        public static string LicenseDialog {
            get {
                return ResourceManager.GetString("LicenseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Update ähnelt.
        /// </summary>
        public static string LiveUpdateDialog {
            get {
                return ResourceManager.GetString("LiveUpdateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More Options ähnelt.
        /// </summary>
        public static string LocalFileMoreOptionsDialog {
            get {
                return ResourceManager.GetString("LocalFileMoreOptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string LocationForm {
            get {
                return ResourceManager.GetString("LocationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        public static string LoginDialog {
            get {
                return ResourceManager.GetString("LoginDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find Full Text ähnelt.
        /// </summary>
        public static string LookupFullTextDialog {
            get {
                return ResourceManager.GetString("LookupFullTextDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find Library Locations ähnelt.
        /// </summary>
        public static string LookupLocationsDialog {
            get {
                return ResourceManager.GetString("LookupLocationsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieve reference by ID ähnelt.
        /// </summary>
        public static string LookupReferenceIdentifierDialog {
            get {
                return ResourceManager.GetString("LookupReferenceIdentifierDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die References ähnelt.
        /// </summary>
        public static string MacroEditorExternalReferencesDialog {
            get {
                return ResourceManager.GetString("MacroEditorExternalReferencesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macro Editor ähnelt.
        /// </summary>
        public static string MacroEditorForm {
            get {
                return ResourceManager.GetString("MacroEditorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knowledge Organizer ähnelt.
        /// </summary>
        public static string MainForm_KnowledgeOrganizer {
            get {
                return ResourceManager.GetString("MainForm_KnowledgeOrganizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Editor ähnelt.
        /// </summary>
        public static string MainForm_ReferenceEditor {
            get {
                return ResourceManager.GetString("MainForm_ReferenceEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task Planner ähnelt.
        /// </summary>
        public static string MainForm_TaskPlanner {
            get {
                return ResourceManager.GetString("MainForm_TaskPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load main form ähnelt.
        /// </summary>
        public static string MainFormLayoutInputBox_Load {
            get {
                return ResourceManager.GetString("MainFormLayoutInputBox_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save main form ähnelt.
        /// </summary>
        public static string MainFormLayoutInputBox_Save {
            get {
                return ResourceManager.GetString("MainFormLayoutInputBox_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Batch Import ISBN Numbers ähnelt.
        /// </summary>
        public static string MassIsbnDownloadDialog {
            get {
                return ResourceManager.GetString("MassIsbnDownloadDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formula Editor ähnelt.
        /// </summary>
        public static string MathEditorForm {
            get {
                return ResourceManager.GetString("MathEditorForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Items ähnelt.
        /// </summary>
        public static string MergeItemsDialog {
            get {
                return ResourceManager.GetString("MergeItemsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More Name Options ähnelt.
        /// </summary>
        public static string MorePersonNameOptionsDialog {
            get {
                return ResourceManager.GetString("MorePersonNameOptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numbering Type ähnelt.
        /// </summary>
        public static string NumberingTypeDialog {
            get {
                return ResourceManager.GetString("NumberingTypeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Credentials ähnelt.
        /// </summary>
        public static string OnlineSearchCredentialConfigurationDialog {
            get {
                return ResourceManager.GetString("OnlineSearchCredentialConfigurationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authentication Required: {0} ähnelt.
        /// </summary>
        public static string OnlineSearchCredentialDialog {
            get {
                return ResourceManager.GetString("OnlineSearchCredentialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Search ähnelt.
        /// </summary>
        public static string OnlineSearchDialogEx {
            get {
                return ResourceManager.GetString("OnlineSearchDialogEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open project ähnelt.
        /// </summary>
        public static string OpenProjectDialog {
            get {
                return ResourceManager.GetString("OpenProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenURL Selection ähnelt.
        /// </summary>
        public static string OpenUrlSelectionDialog {
            get {
                return ResourceManager.GetString("OpenUrlSelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string OptionsDialog {
            get {
                return ResourceManager.GetString("OptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import or Export Settings ähnelt.
        /// </summary>
        public static string OptionsImportExportDialog {
            get {
                return ResourceManager.GetString("OptionsImportExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Numbering ähnelt.
        /// </summary>
        public static string OrderedListDialog {
            get {
                return ResourceManager.GetString("OrderedListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage organizational settings ähnelt.
        /// </summary>
        public static string OrganizationSettingsAdminDialog {
            get {
                return ResourceManager.GetString("OrganizationSettingsAdminDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export settings ähnelt.
        /// </summary>
        public static string OrganizationSettingsExportDialog {
            get {
                return ResourceManager.GetString("OrganizationSettingsExportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import settings ähnelt.
        /// </summary>
        public static string OrganizationSettingsImportDialog {
            get {
                return ResourceManager.GetString("OrganizationSettingsImportDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page Margins ähnelt.
        /// </summary>
        public static string PageSetupDialog {
            get {
                return ResourceManager.GetString("PageSetupDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paragraph ähnelt.
        /// </summary>
        public static string ParagraphFormatDialog {
            get {
                return ResourceManager.GetString("ParagraphFormatDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodical ähnelt.
        /// </summary>
        public static string PeriodicalForm {
            get {
                return ResourceManager.GetString("PeriodicalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodicals ähnelt.
        /// </summary>
        public static string PeriodicalList {
            get {
                return ResourceManager.GetString("PeriodicalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Person or Organization ähnelt.
        /// </summary>
        public static string PersonForm {
            get {
                return ResourceManager.GetString("PersonForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons and Organizations ähnelt.
        /// </summary>
        public static string PersonList {
            get {
                return ResourceManager.GetString("PersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Persons and Organizations ähnelt.
        /// </summary>
        public static string PersonsDialog {
            get {
                return ResourceManager.GetString("PersonsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page Numbering ähnelt.
        /// </summary>
        public static string PlaceholderEntryPageNumbersDialog {
            get {
                return ResourceManager.GetString("PlaceholderEntryPageNumbersDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prefix and Suffix  ähnelt.
        /// </summary>
        public static string PlaceholderEntryPrefixSuffixDialog {
            get {
                return ResourceManager.GetString("PlaceholderEntryPrefixSuffixDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        public static string PrintForm {
            get {
                return ResourceManager.GetString("PrintForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working… ähnelt.
        /// </summary>
        public static string ProgressDialog {
            get {
                return ResourceManager.GetString("ProgressDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Properties ähnelt.
        /// </summary>
        public static string ProjectPropertiesDialog {
            get {
                return ResourceManager.GetString("ProjectPropertiesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spelling ähnelt.
        /// </summary>
        public static string ProofingToolsDialog {
            get {
                return ResourceManager.GetString("ProofingToolsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Proxy Settings ähnelt.
        /// </summary>
        public static string ProxyConfigurationDialog {
            get {
                return ResourceManager.GetString("ProxyConfigurationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LaTeX Assistant ähnelt.
        /// </summary>
        public static string PublicationAssistant {
            get {
                return ResourceManager.GetString("PublicationAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Publisher ähnelt.
        /// </summary>
        public static string PublisherForm {
            get {
                return ResourceManager.GetString("PublisherForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of Publishers ähnelt.
        /// </summary>
        public static string PublisherList {
            get {
                return ResourceManager.GetString("PublisherList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit Citavi ähnelt.
        /// </summary>
        public static string QuitCitaviDialog {
            get {
                return ResourceManager.GetString("QuitCitaviDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recycle bin ähnelt.
        /// </summary>
        public static string RecycleBinDialog {
            get {
                return ResourceManager.GetString("RecycleBinDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete References ähnelt.
        /// </summary>
        public static string ReferenceDeletionDialog {
            get {
                return ResourceManager.GetString("ReferenceDeletionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table View Columns ähnelt.
        /// </summary>
        public static string ReferenceGridColumnsForm {
            get {
                return ResourceManager.GetString("ReferenceGridColumnsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table View ähnelt.
        /// </summary>
        public static string ReferenceGridForm {
            get {
                return ResourceManager.GetString("ReferenceGridForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group References – Table View ähnelt.
        /// </summary>
        public static string ReferenceGridGroupsForm {
            get {
                return ResourceManager.GetString("ReferenceGridGroupsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieve by DOI Name ähnelt.
        /// </summary>
        public static string ReferenceIdentifierDownloadOptionsDialog_Doi {
            get {
                return ResourceManager.GetString("ReferenceIdentifierDownloadOptionsDialog_Doi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieve by ISBN ähnelt.
        /// </summary>
        public static string ReferenceIdentifierDownloadOptionsDialog_Isbn {
            get {
                return ResourceManager.GetString("ReferenceIdentifierDownloadOptionsDialog_Isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retrieve by PubMed ID ähnelt.
        /// </summary>
        public static string ReferenceIdentifierDownloadOptionsDialog_PubMedId {
            get {
                return ResourceManager.GetString("ReferenceIdentifierDownloadOptionsDialog_PubMedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace ähnelt.
        /// </summary>
        public static string ReplacementDialog {
            get {
                return ResourceManager.GetString("ReplacementDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replacements ähnelt.
        /// </summary>
        public static string ReplacementListDialog {
            get {
                return ResourceManager.GetString("ReplacementListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Connections ähnelt.
        /// </summary>
        public static string RetrievalDefinitionFavoritesDialog {
            get {
                return ResourceManager.GetString("RetrievalDefinitionFavoritesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string RtfForm {
            get {
                return ResourceManager.GetString("RtfForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample Projects ähnelt.
        /// </summary>
        public static string SampleProjectsDialog {
            get {
                return ResourceManager.GetString("SampleProjectsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save a copy as new local project ähnelt.
        /// </summary>
        public static string SaveProjectAsNewDesktopLocalProjectDialog {
            get {
                return ResourceManager.GetString("SaveProjectAsNewDesktopLocalProjectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define Search ähnelt.
        /// </summary>
        public static string SearchDetailForm {
            get {
                return ResourceManager.GetString("SearchDetailForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string SearchForm {
            get {
                return ResourceManager.GetString("SearchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search and Replace ähnelt.
        /// </summary>
        public static string SearchReplaceForm {
            get {
                return ResourceManager.GetString("SearchReplaceForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Series ähnelt.
        /// </summary>
        public static string SeriesTitleForm {
            get {
                return ResourceManager.GetString("SeriesTitleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die List of Series ähnelt.
        /// </summary>
        public static string SeriesTitleList {
            get {
                return ResourceManager.GetString("SeriesTitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short Title ähnelt.
        /// </summary>
        public static string ShortTitleDialog {
            get {
                return ResourceManager.GetString("ShortTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference Types ähnelt.
        /// </summary>
        public static string ShowReferenceTypeSelectionDialog {
            get {
                return ResourceManager.GetString("ShowReferenceTypeSelectionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Knowledge Items ähnelt.
        /// </summary>
        public static string SortKnowledgeItemsForm {
            get {
                return ResourceManager.GetString("SortKnowledgeItemsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort References ähnelt.
        /// </summary>
        public static string SortReferencesCustomDialog {
            get {
                return ResourceManager.GetString("SortReferencesCustomDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Tasks ähnelt.
        /// </summary>
        public static string SortTasksCustomDialog {
            get {
                return ResourceManager.GetString("SortTasksCustomDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi 6 Welcome Screen ähnelt.
        /// </summary>
        public static string StartForm {
            get {
                return ResourceManager.GetString("StartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samples and Information ähnelt.
        /// </summary>
        public static string StartFormInfoDialog {
            get {
                return ResourceManager.GetString("StartFormInfoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support Information ähnelt.
        /// </summary>
        public static string SupportInformationDialog {
            get {
                return ResourceManager.GetString("SupportInformationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tab Stops ähnelt.
        /// </summary>
        public static string TabStopDialog {
            get {
                return ResourceManager.GetString("TabStopDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Import Definitions ähnelt.
        /// </summary>
        public static string TagDefinitionFavoritesDialog {
            get {
                return ResourceManager.GetString("TagDefinitionFavoritesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task ähnelt.
        /// </summary>
        public static string TaskItemForm {
            get {
                return ResourceManager.GetString("TaskItemForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Task ähnelt.
        /// </summary>
        public static string TaskItemForm_ProjectTask {
            get {
                return ResourceManager.GetString("TaskItemForm_ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template Conditions ähnelt.
        /// </summary>
        public static string TemplateConditionDialog {
            get {
                return ResourceManager.GetString("TemplateConditionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic BibTeX Export ähnelt.
        /// </summary>
        public static string TeXPublicationForm {
            get {
                return ResourceManager.GetString("TeXPublicationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text-Based Filter ähnelt.
        /// </summary>
        public static string TextBasedFilterDialog {
            get {
                return ResourceManager.GetString("TextBasedFilterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Export ähnelt.
        /// </summary>
        public static string TextExportForm {
            get {
                return ResourceManager.GetString("TextExportForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungrouped References ähnelt.
        /// </summary>
        public static string UngroupedReferencesSettingsForm {
            get {
                return ResourceManager.GetString("UngroupedReferencesSettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bullets ähnelt.
        /// </summary>
        public static string UnorderedListDialog {
            get {
                return ResourceManager.GetString("UnorderedListDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Folder for User Files ähnelt.
        /// </summary>
        public static string UserDataFolderPathDialog {
            get {
                return ResourceManager.GetString("UserDataFolderPathDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zoomed Editor ähnelt.
        /// </summary>
        public static string ZoomForm {
            get {
                return ResourceManager.GetString("ZoomForm", resourceCulture);
            }
        }
    }
}
