//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguagesAndCultures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagesAndCultures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.LanguagesAndCultures", typeof(LanguagesAndCultures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afar.
        /// </summary>
        public static string AA {
            get {
                return ResourceManager.GetString("AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abkhaz.
        /// </summary>
        public static string AB {
            get {
                return ResourceManager.GetString("AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amharic.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapudungun.
        /// </summary>
        public static string ARN {
            get {
                return ResourceManager.GetString("ARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assamese.
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azeri.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azeri (Latin).
        /// </summary>
        public static string AZ_LATN {
            get {
                return ResourceManager.GetString("AZ_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bashkir.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bengali.
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibetan.
        /// </summary>
        public static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breton.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnian.
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnian (Cyrillic).
        /// </summary>
        public static string BS_CYRL {
            get {
                return ResourceManager.GetString("BS_CYRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosian (Latin).
        /// </summary>
        public static string BS_LATN {
            get {
                return ResourceManager.GetString("BS_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherokee.
        /// </summary>
        public static string CHR {
            get {
                return ResourceManager.GetString("CHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cherokee (Cherokee).
        /// </summary>
        public static string CHR_CHER {
            get {
                return ResourceManager.GetString("CHR_CHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsican.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welsh.
        /// </summary>
        public static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Sorbian.
        /// </summary>
        public static string DSB {
            get {
                return ResourceManager.GetString("DSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divehi.
        /// </summary>
        public static string DV {
            get {
                return ResourceManager.GetString("DV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string EL {
            get {
                return ResourceManager.GetString("EL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperanto.
        /// </summary>
        public static string EO {
            get {
                return ResourceManager.GetString("EO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basque.
        /// </summary>
        public static string EU {
            get {
                return ResourceManager.GetString("EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string FA {
            get {
                return ResourceManager.GetString("FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulah.
        /// </summary>
        public static string FF {
            get {
                return ResourceManager.GetString("FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulah (Latin).
        /// </summary>
        public static string FF_LATN {
            get {
                return ResourceManager.GetString("FF_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filipino.
        /// </summary>
        public static string FIL {
            get {
                return ResourceManager.GetString("FIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroese.
        /// </summary>
        public static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frisian.
        /// </summary>
        public static string FY {
            get {
                return ResourceManager.GetString("FY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scottish Gaelic.
        /// </summary>
        public static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician.
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guarani.
        /// </summary>
        public static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alsatian.
        /// </summary>
        public static string GSW {
            get {
                return ResourceManager.GetString("GSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gujarati.
        /// </summary>
        public static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausa.
        /// </summary>
        public static string HA {
            get {
                return ResourceManager.GetString("HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hausa (Latin).
        /// </summary>
        public static string HA_LATN {
            get {
                return ResourceManager.GetString("HA_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawaiian.
        /// </summary>
        public static string HAW {
            get {
                return ResourceManager.GetString("HAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string HE {
            get {
                return ResourceManager.GetString("HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string HI {
            get {
                return ResourceManager.GetString("HI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Sorbian.
        /// </summary>
        public static string HSB {
            get {
                return ResourceManager.GetString("HSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string HY {
            get {
                return ResourceManager.GetString("HY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igbo.
        /// </summary>
        public static string IG {
            get {
                return ResourceManager.GetString("IG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yi.
        /// </summary>
        public static string II {
            get {
                return ResourceManager.GetString("II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inuktitut.
        /// </summary>
        public static string IU {
            get {
                return ResourceManager.GetString("IU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inuktitut (Syllabics).
        /// </summary>
        public static string IU_CANS {
            get {
                return ResourceManager.GetString("IU_CANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inutktitut (Latin).
        /// </summary>
        public static string IU_LATN {
            get {
                return ResourceManager.GetString("IU_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string JA {
            get {
                return ResourceManager.GetString("JA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basa Jawa.
        /// </summary>
        public static string JV {
            get {
                return ResourceManager.GetString("JV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basa Jawa (Latin).
        /// </summary>
        public static string JV_LATN {
            get {
                return ResourceManager.GetString("JV_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string KA {
            get {
                return ResourceManager.GetString("KA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh.
        /// </summary>
        public static string KK {
            get {
                return ResourceManager.GetString("KK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenlandic.
        /// </summary>
        public static string KL {
            get {
                return ResourceManager.GetString("KL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kannada.
        /// </summary>
        public static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string KO {
            get {
                return ResourceManager.GetString("KO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konkani.
        /// </summary>
        public static string KOK {
            get {
                return ResourceManager.GetString("KOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Kurdish.
        /// </summary>
        public static string KU {
            get {
                return ResourceManager.GetString("KU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Kurdish (Arabic).
        /// </summary>
        public static string KU_ARAB {
            get {
                return ResourceManager.GetString("KU_ARAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        public static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourgish.
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lao.
        /// </summary>
        public static string LO {
            get {
                return ResourceManager.GetString("LO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malagasy.
        /// </summary>
        public static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maori.
        /// </summary>
        public static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian (FYROM).
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        public static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian (Cyrillic).
        /// </summary>
        public static string MN_CYRL {
            get {
                return ResourceManager.GetString("MN_CYRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mongolian (Traditional Mongolian).
        /// </summary>
        public static string MN_MONG {
            get {
                return ResourceManager.GetString("MN_MONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohawk.
        /// </summary>
        public static string MOH {
            get {
                return ResourceManager.GetString("MOH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathi.
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burmese.
        /// </summary>
        public static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (Bokmål).
        /// </summary>
        public static string NB {
            get {
                return ResourceManager.GetString("NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepali.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (Nynorsk).
        /// </summary>
        public static string NN {
            get {
                return ResourceManager.GetString("NN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;Ko.
        /// </summary>
        public static string NQO {
            get {
                return ResourceManager.GetString("NQO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesotho sa Leboa.
        /// </summary>
        public static string NSO {
            get {
                return ResourceManager.GetString("NSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occitan.
        /// </summary>
        public static string OC {
            get {
                return ResourceManager.GetString("OC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oromoo.
        /// </summary>
        public static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oriya.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjabi.
        /// </summary>
        public static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punjabi (Arabic).
        /// </summary>
        public static string PA_ARAB {
            get {
                return ResourceManager.GetString("PA_ARAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari.
        /// </summary>
        public static string PRS {
            get {
                return ResourceManager.GetString("PRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        public static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K&apos;iche.
        /// </summary>
        public static string QUT {
            get {
                return ResourceManager.GetString("QUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quechua.
        /// </summary>
        public static string QUZ {
            get {
                return ResourceManager.GetString("QUZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romansh.
        /// </summary>
        public static string RM {
            get {
                return ResourceManager.GetString("RM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinyarwanda.
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanskrit.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakha.
        /// </summary>
        public static string SAH {
            get {
                return ResourceManager.GetString("SAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sindhi.
        /// </summary>
        public static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sindhi (Arabic).
        /// </summary>
        public static string SD_ARAB {
            get {
                return ResourceManager.GetString("SD_ARAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sami (Northern).
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinhala.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sami (Southern).
        /// </summary>
        public static string SMA {
            get {
                return ResourceManager.GetString("SMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sami (Lule).
        /// </summary>
        public static string SMJ {
            get {
                return ResourceManager.GetString("SMJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sami (Inari).
        /// </summary>
        public static string SMN {
            get {
                return ResourceManager.GetString("SMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sami (Skolt).
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chiShona.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chiShona (Latin).
        /// </summary>
        public static string SN_LATN {
            get {
                return ResourceManager.GetString("SN_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soomaali.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string SQ {
            get {
                return ResourceManager.GetString("SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian (Cyrillic).
        /// </summary>
        public static string SR_CYRL {
            get {
                return ResourceManager.GetString("SR_CYRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian (Latin).
        /// </summary>
        public static string SR_LATN {
            get {
                return ResourceManager.GetString("SR_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesotho.
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiswahili.
        /// </summary>
        public static string SW {
            get {
                return ResourceManager.GetString("SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syriac.
        /// </summary>
        public static string SYR {
            get {
                return ResourceManager.GetString("SYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        public static string TA {
            get {
                return ResourceManager.GetString("TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telugu.
        /// </summary>
        public static string TE {
            get {
                return ResourceManager.GetString("TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajik.
        /// </summary>
        public static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkmen.
        /// </summary>
        public static string TK {
            get {
                return ResourceManager.GetString("TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setswana.
        /// </summary>
        public static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xitsonga.
        /// </summary>
        public static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatar.
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamazight.
        /// </summary>
        public static string TZM {
            get {
                return ResourceManager.GetString("TZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamazight (Latin).
        /// </summary>
        public static string TZM_LATN {
            get {
                return ResourceManager.GetString("TZM_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamazight (Tifinagh).
        /// </summary>
        public static string TZM_TFNG {
            get {
                return ResourceManager.GetString("TZM_TFNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyghur.
        /// </summary>
        public static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UK {
            get {
                return ResourceManager.GetString("UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        public static string UR {
            get {
                return ResourceManager.GetString("UR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek (Cyrillic).
        /// </summary>
        public static string UZ_CYRL {
            get {
                return ResourceManager.GetString("UZ_CYRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek (Latin).
        /// </summary>
        public static string UZ_LATN {
            get {
                return ResourceManager.GetString("UZ_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolof.
        /// </summary>
        public static string WO {
            get {
                return ResourceManager.GetString("WO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xhosa.
        /// </summary>
        public static string XH {
            get {
                return ResourceManager.GetString("XH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoruba.
        /// </summary>
        public static string YO {
            get {
                return ResourceManager.GetString("YO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Morrocan Tamazight.
        /// </summary>
        public static string ZGH {
            get {
                return ResourceManager.GetString("ZGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Morrocan Tamazight (Tifinagh).
        /// </summary>
        public static string ZGH_TFNG {
            get {
                return ResourceManager.GetString("ZGH_TFNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string ZH {
            get {
                return ResourceManager.GetString("ZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified) Legacy.
        /// </summary>
        public static string ZH_CHS {
            get {
                return ResourceManager.GetString("ZH_CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified) Legacy.
        /// </summary>
        public static string ZH_CHT {
            get {
                return ResourceManager.GetString("ZH_CHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Simplified).
        /// </summary>
        public static string ZH_HANS {
            get {
                return ResourceManager.GetString("ZH_HANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Traditional).
        /// </summary>
        public static string ZH_HANT {
            get {
                return ResourceManager.GetString("ZH_HANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulu.
        /// </summary>
        public static string ZU {
            get {
                return ResourceManager.GetString("ZU", resourceCulture);
            }
        }
    }
}
