//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Picker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Picker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.Picker", typeof(Picker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account….
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Account_Profile {
            get {
                return ResourceManager.GetString("Account_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as local file to the current Citavi reference.
        /// </summary>
        internal static string AddAsLocalFileToTheCurrentCitaviReference {
            get {
                return ResourceManager.GetString("AddAsLocalFileToTheCurrentCitaviReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in Citavi.
        /// </summary>
        internal static string AddKindleQuotation {
            get {
                return ResourceManager.GetString("AddKindleQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in Citavi.
        /// </summary>
        internal static string AddKindleReference {
            get {
                return ResourceManager.GetString("AddKindleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as local file to the current Citavi reference.
        /// </summary>
        internal static string AddPdfAsLocalFile {
            get {
                return ResourceManager.GetString("AddPdfAsLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF document as reference.
        /// </summary>
        internal static string AddPdfAsReference {
            get {
                return ResourceManager.GetString("AddPdfAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF document and save Selection.
        /// </summary>
        internal static string AddPDFDocumentAndSaveSelection {
            get {
                return ResourceManager.GetString("AddPDFDocumentAndSaveSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add PDF document as reference.
        /// </summary>
        internal static string AddPDFDocumentAsReference {
            get {
                return ResourceManager.GetString("AddPDFDocumentAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add reference and add selection.
        /// </summary>
        internal static string AddReferenceAndAddSelection {
            get {
                return ResourceManager.GetString("AddReferenceAndAddSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add screen as screenshot.
        /// </summary>
        internal static string AddScreenAsScreenshot {
            get {
                return ResourceManager.GetString("AddScreenAsScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected image.
        /// </summary>
        internal static string AddSelectedImage {
            get {
                return ResourceManager.GetString("AddSelectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selection as image quotation.
        /// </summary>
        internal static string AddSelectionAsImageQuotation {
            get {
                return ResourceManager.GetString("AddSelectionAsImageQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selection as quotation.
        /// </summary>
        internal static string AddSelectionAsQuotation {
            get {
                return ResourceManager.GetString("AddSelectionAsQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add text selection.
        /// </summary>
        internal static string AddTextSelection {
            get {
                return ResourceManager.GetString("AddTextSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Citavi project by DOI.
        /// </summary>
        internal static string AddToCitaviProjectByDOI {
            get {
                return ResourceManager.GetString("AddToCitaviProjectByDOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Citavi project by ISBN.
        /// </summary>
        internal static string AddToCitaviProjectByISBN {
            get {
                return ResourceManager.GetString("AddToCitaviProjectByISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Citavi project by PubMed ID.
        /// </summary>
        internal static string AddToCitaviProjectByPMID {
            get {
                return ResourceManager.GetString("AddToCitaviProjectByPMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add webpage as reference.
        /// </summary>
        internal static string AddWebPageAsReference {
            get {
                return ResourceManager.GetString("AddWebPageAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker for Adobe Acrobat and Adobe Reader.
        /// </summary>
        internal static string AdobePicker {
            get {
                return ResourceManager.GetString("AdobePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show reference in Citavi directly and skip this message in the future..
        /// </summary>
        internal static string AlreadyInProject_AutoShowReference {
            get {
                return ResourceManager.GetString("AlreadyInProject_AutoShowReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A journal article with the same DOI name is already in the current project..
        /// </summary>
        internal static string AlreadyInProject_DOI {
            get {
                return ResourceManager.GetString("AlreadyInProject_DOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book with the same ISBN is already in the current project..
        /// </summary>
        internal static string AlreadyInProject_ISBN {
            get {
                return ResourceManager.GetString("AlreadyInProject_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A journal article with the same PubMed ID is already in the current project..
        /// </summary>
        internal static string AlreadyInProject_PMID {
            get {
                return ResourceManager.GetString("AlreadyInProject_PMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as abstract.
        /// </summary>
        internal static string AsAbstract {
            get {
                return ResourceManager.GetString("AsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as cover art.
        /// </summary>
        internal static string AsCoverArt {
            get {
                return ResourceManager.GetString("AsCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as image quotation.
        /// </summary>
        internal static string AsImageQuotation {
            get {
                return ResourceManager.GetString("AsImageQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as keyword.
        /// </summary>
        internal static string AsKeyword {
            get {
                return ResourceManager.GetString("AsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as quotation.
        /// </summary>
        internal static string AsQuotation {
            get {
                return ResourceManager.GetString("AsQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to …as table of contents.
        /// </summary>
        internal static string AsTableOfContents {
            get {
                return ResourceManager.GetString("AsTableOfContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for references….
        /// </summary>
        internal static string BibliographyReferencesProgressText {
            get {
                return ResourceManager.GetString("BibliographyReferencesProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References cited.
        /// </summary>
        internal static string BibliographyReferencesTitle {
            get {
                return ResourceManager.GetString("BibliographyReferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker for Google Chrome.
        /// </summary>
        internal static string ChromePicker {
            get {
                return ResourceManager.GetString("ChromePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} reference(s) found. Citavi will now search for the full text..
        /// </summary>
        internal static string CitaviFoundReferencesToImportDirectly {
            get {
                return ResourceManager.GetString("CitaviFoundReferencesToImportDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker has determined that Citavi is not running.
        ///Please start Citavi and then repeat the command you just used.
        ///
        ///.
        /// </summary>
        internal static string CitaviIsNotRunning {
            get {
                return ResourceManager.GetString("CitaviIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to import the references..
        /// </summary>
        internal static string ClickHereToImportTheReferences {
            get {
                return ResourceManager.GetString("ClickHereToImportTheReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker {0} for {1} is an extension for the software program “Citavi® Reference Management and Knowledge Organization”.
        ///.
        /// </summary>
        internal static string Copyrigth {
            get {
                return ResourceManager.GetString("Copyrigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selection and URL to Clipboard.
        /// </summary>
        internal static string CopySelectionAndURLToClipboard {
            get {
                return ResourceManager.GetString("CopySelectionAndURLToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel selection.
        /// </summary>
        internal static string Deselect_All {
            get {
                return ResourceManager.GetString("Deselect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create activity log.
        /// </summary>
        internal static string EnableTrace {
            get {
                return ResourceManager.GetString("EnableTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team of developers has been informed and will resolve the issue as soon as possible..
        /// </summary>
        internal static string Error_Text_1 {
            get {
                return ResourceManager.GetString("Error_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please help us find the source of the error..
        /// </summary>
        internal static string Error_Text_2 {
            get {
                return ResourceManager.GetString("Error_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in &quot;{0}&quot;..
        /// </summary>
        internal static string ExistsInProject {
            get {
                return ResourceManager.GetString("ExistsInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker for Firefox.
        /// </summary>
        internal static string FFPicker {
            get {
                return ResourceManager.GetString("FFPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker for Internet Explorer.
        /// </summary>
        internal static string IEPicker {
            get {
                return ResourceManager.GetString("IEPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of the complete page.
        /// </summary>
        internal static string ImageOfTheCompletePage {
            get {
                return ResourceManager.GetString("ImageOfTheCompletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of the current window.
        /// </summary>
        internal static string ImageOfTheCurrentWindow {
            get {
                return ResourceManager.GetString("ImageOfTheCurrentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing reference(s) to {0}….
        /// </summary>
        internal static string ImportKindleReference {
            get {
                return ResourceManager.GetString("ImportKindleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Citavi Picker can&apos;t import local files..
        /// </summary>
        internal static string ImportLocalFilesNotSupported {
            get {
                return ResourceManager.GetString("ImportLocalFilesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the references you want to import:.
        /// </summary>
        internal static string ImportTitleLabel {
            get {
                return ResourceManager.GetString("ImportTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also save as PDF.
        /// </summary>
        internal static string NewsPaperHtmlToPdf {
            get {
                return ResourceManager.GetString("NewsPaperHtmlToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Citavi project is currently open..
        /// </summary>
        internal static string NoProjectOpen {
            get {
                return ResourceManager.GetString("NoProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results were found for these criteria..
        /// </summary>
        internal static string NoResultsWereFoundForTheseCriteria {
            get {
                return ResourceManager.GetString("NoResultsWereFoundForTheseCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Citavi Hunter.
        /// </summary>
        internal static string OptionsDialogHunterCheckbox {
            get {
                return ResourceManager.GetString("OptionsDialogHunterCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Hunters help the Picker detect references that can be imported from certain online databases (PubMed, Scholar, ArXiv.org). When search results are displayed, the Picker inserts a blue bar at the very bottom of the page. Click the bar to add the references to the current Citavi project..
        /// </summary>
        internal static string OptionsDialogHunterInfo {
            get {
                return ResourceManager.GetString("OptionsDialogHunterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically detect search results on webpages..
        /// </summary>
        internal static string OptionsDialogHunterTitle {
            get {
                return ResourceManager.GetString("OptionsDialogHunterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable identifier detection (ISBN, DOI, PubMed, PMCID, arXiv) and show icons..
        /// </summary>
        internal static string OptionsDialogISBNCheckbox {
            get {
                return ResourceManager.GetString("OptionsDialogISBNCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier detection.
        /// </summary>
        internal static string OptionsDialogISBNDOITitle {
            get {
                return ResourceManager.GetString("OptionsDialogISBNDOITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi can detect identifiers (ISBN, DOI, PubMed, PMCID, arXiv) on webpages and designate them with the Citavi icon ISBNs and DOIs on webpages and highlight them with the Citavi icon. Click the icon to perform a search for the item&apos;s citation information and then save it in the current Citavi project. In Citavi you can select the catalogs that should be used for the ISBN search by clicking Tools &gt; Options &gt; Search..
        /// </summary>
        internal static string OptionsDialogISBNInfo {
            get {
                return ResourceManager.GetString("OptionsDialogISBNInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display notifications.
        /// </summary>
        internal static string OptionsDialogShowImportMsgboxCheckbox {
            get {
                return ResourceManager.GetString("OptionsDialogShowImportMsgboxCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a notification when the Picker successfully transfers information to Citavi..
        /// </summary>
        internal static string OptionsDialogShowImportMsgboxInfo {
            get {
                return ResourceManager.GetString("OptionsDialogShowImportMsgboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for Notifications.
        /// </summary>
        internal static string OptionsDialogShowImportMsgboxTitle {
            get {
                return ResourceManager.GetString("OptionsDialogShowImportMsgboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string Panel_Abstract {
            get {
                return ResourceManager.GetString("Panel_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&apos;addPdfAsLocalFileBtn&apos;&gt;Add as local file to the current Citavi reference&lt;/a&gt;.
        /// </summary>
        internal static string Panel_AddPdfAsLocalFile_link {
            get {
                return ResourceManager.GetString("Panel_AddPdfAsLocalFile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&apos;webPageAsNewReferenceBtn&apos;&gt;Add PDF as reference&lt;/a&gt;.
        /// </summary>
        internal static string Panel_AddPdfAsReference_link {
            get {
                return ResourceManager.GetString("Panel_AddPdfAsReference_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;red&apos;&gt;Add PDF as reference&lt;/span&gt;.
        /// </summary>
        internal static string Panel_AddPDFDocumentAsReference {
            get {
                return ResourceManager.GetString("Panel_AddPDFDocumentAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as….
        /// </summary>
        internal static string Panel_AddSelectionAsField {
            get {
                return ResourceManager.GetString("Panel_AddSelectionAsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selection to the current reference.
        /// </summary>
        internal static string Panel_AddSelectionCurrentReference {
            get {
                return ResourceManager.GetString("Panel_AddSelectionCurrentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selection as….
        /// </summary>
        internal static string Panel_AddTextSelection {
            get {
                return ResourceManager.GetString("Panel_AddTextSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a id=&apos;webPageAsLocation&apos;&gt;Add URL to the current Citavi reference&lt;/a&gt;.
        /// </summary>
        internal static string Panel_AddWebPageAsLocation {
            get {
                return ResourceManager.GetString("Panel_AddWebPageAsLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;red&apos;&gt;Add webpage as new reference&lt;/span&gt;.
        /// </summary>
        internal static string Panel_AddWebPageAsReference {
            get {
                return ResourceManager.GetString("Panel_AddWebPageAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;red&apos; id=&apos;webPageAsNewReferenceBtn&apos;&gt;Add webpage as reference&lt;/span&gt;.
        /// </summary>
        internal static string Panel_AddWebPageAsReference_link {
            get {
                return ResourceManager.GetString("Panel_AddWebPageAsReference_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Panel_Back {
            get {
                return ResourceManager.GetString("Panel_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only import selected references.
        /// </summary>
        internal static string Panel_BibliographyImport_ImportSelectedReference {
            get {
                return ResourceManager.GetString("Panel_BibliographyImport_ImportSelectedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also import all cited references.
        /// </summary>
        internal static string Panel_BibliographyImport_ImportSelectedReferenceAndCitedReferences {
            get {
                return ResourceManager.GetString("Panel_BibliographyImport_ImportSelectedReferenceAndCitedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display cited references and then select.
        /// </summary>
        internal static string Panel_BibliographyImport_ImportSelectedReferenceAndCitedReferences2 {
            get {
                return ResourceManager.GetString("Panel_BibliographyImport_ImportSelectedReferenceAndCitedReferences2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can take a moment..
        /// </summary>
        internal static string Panel_BibliographyImportInfo_Info {
            get {
                return ResourceManager.GetString("Panel_BibliographyImportInfo_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected reference cites {0} additional references.
        /// </summary>
        internal static string Panel_BibliographyImportInfo_Title {
            get {
                return ResourceManager.GetString("Panel_BibliographyImportInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Panel_Button_Go {
            get {
                return ResourceManager.GetString("Panel_Button_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?:.
        /// </summary>
        internal static string Panel_ChooseAnAction {
            get {
                return ResourceManager.GetString("Panel_ChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the references you want to import.&lt;br/&gt;Then, click Go..
        /// </summary>
        internal static string Panel_ChooseAnAction_Hunter {
            get {
                return ResourceManager.GetString("Panel_ChooseAnAction_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Picker has determined that Citavi is not running.&lt;br&gt;&lt;br&gt;Please start Citavi and then repeat the command you just used..
        /// </summary>
        internal static string Panel_CitaviIsNotRunning {
            get {
                return ResourceManager.GetString("Panel_CitaviIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi Web.
        /// </summary>
        internal static string Panel_CitaviWebLogin {
            get {
                return ResourceManager.GetString("Panel_CitaviWebLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection and URL.
        /// </summary>
        internal static string Panel_CopySelectionAndURLToClipboard_1 {
            get {
                return ResourceManager.GetString("Panel_CopySelectionAndURLToClipboard_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to the Clipboard.
        /// </summary>
        internal static string Panel_CopySelectionAndURLToClipboard_2 {
            get {
                return ResourceManager.GetString("Panel_CopySelectionAndURLToClipboard_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Panel_Error {
            get {
                return ResourceManager.GetString("Panel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Panel_Help {
            get {
                return ResourceManager.GetString("Panel_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All references.
        /// </summary>
        internal static string Panel_Hunter_SelectAll {
            get {
                return ResourceManager.GetString("Panel_Hunter_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Panel_ImportHunterReferences {
            get {
                return ResourceManager.GetString("Panel_ImportHunterReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string Panel_Keywords {
            get {
                return ResourceManager.GetString("Panel_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string Panel_More {
            get {
                return ResourceManager.GetString("Panel_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project for the import:.
        /// </summary>
        internal static string Panel_ProjectSelection {
            get {
                return ResourceManager.GetString("Panel_ProjectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Panel_QuickHelp {
            get {
                return ResourceManager.GetString("Panel_QuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Panel_Settings {
            get {
                return ResourceManager.GetString("Panel_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an article with the same DOI is already in the project, the reference will be automatically shown when the Picker symbol is clicked..
        /// </summary>
        internal static string Panel_Settings_AlreadyInProject_AutoShowReference_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_AlreadyInProject_AutoShowReference_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to reference.
        /// </summary>
        internal static string Panel_Settings_AlreadyInProject_AutoShowReference_Title {
            get {
                return ResourceManager.GetString("Panel_Settings_AlreadyInProject_AutoShowReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only enable this option if you are asked to do so by the Citavi support team..
        /// </summary>
        internal static string Panel_Settings_EnableTrace_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_EnableTrace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Citavi Hunter helps the Picker detect references that can be imported from certain online databases..
        /// </summary>
        internal static string Panel_Settings_Hunter_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_Hunter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi will save the PDFs it can find in your project..
        /// </summary>
        internal static string Panel_Settings_ImportPdf_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_ImportPdf_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDFs automatically.
        /// </summary>
        internal static string Panel_Settings_ImportPdf_Title {
            get {
                return ResourceManager.GetString("Panel_Settings_ImportPdf_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this option is selected, any cited references that are found can be imported along with the original item..
        /// </summary>
        internal static string Panel_Settings_LookupBibliography_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_LookupBibliography_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import cited references.
        /// </summary>
        internal static string Panel_Settings_LookupBibliography_Title {
            get {
                return ResourceManager.GetString("Panel_Settings_LookupBibliography_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a notification when the Picker successfully transfers information to Citavi..
        /// </summary>
        internal static string Panel_Settings_MsgBox_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_MsgBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citavi can detect identifiers (ISBN, DOI, PubMed, PMCID, arXiv) on webpages. Click the icon to import the item into Citavi..
        /// </summary>
        internal static string Panel_Settings_ReferenceIdentifier_Text {
            get {
                return ResourceManager.GetString("Panel_Settings_ReferenceIdentifier_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier detection.
        /// </summary>
        internal static string Panel_Settings_ReferenceIdentifier_Title {
            get {
                return ResourceManager.GetString("Panel_Settings_ReferenceIdentifier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create activity log.
        /// </summary>
        internal static string Panel_Settings_Settings_EnableTrace {
            get {
                return ResourceManager.GetString("Panel_Settings_Settings_EnableTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        internal static string Panel_TextQuotation {
            get {
                return ResourceManager.GetString("Panel_TextQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table of contents.
        /// </summary>
        internal static string Panel_ToC {
            get {
                return ResourceManager.GetString("Panel_ToC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Panel_Warning {
            get {
                return ResourceManager.GetString("Panel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy PDF file to Citavi Attachments folder.
        /// </summary>
        internal static string PdfOptionsDialogCopyPdf {
            get {
                return ResourceManager.GetString("PdfOptionsDialogCopyPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Picker imports bibliographic information for an online PDF file into the current Citavi project.
        ///
        ///You can also save a copy of the PDF file on your computer and rename it with the short title that Citavi automatically creates for each reference..
        /// </summary>
        internal static string PdfOptionsDialogInfoLabel {
            get {
                return ResourceManager.GetString("PdfOptionsDialogInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename PDF file with Citavi short title.
        /// </summary>
        internal static string PdfOptionsDialogRenamePdf {
            get {
                return ResourceManager.GetString("PdfOptionsDialogRenamePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project:.
        /// </summary>
        internal static string ProjectSelection {
            get {
                return ResourceManager.GetString("ProjectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected text is on its way to Citavi..
        /// </summary>
        internal static string ReferenceDataSentToCitavi {
            get {
                return ResourceManager.GetString("ReferenceDataSentToCitavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reference is on its way to Citavi..
        /// </summary>
        internal static string ReferenceSentToCitavi {
            get {
                return ResourceManager.GetString("ReferenceSentToCitavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your references are on their way to Citavi..
        /// </summary>
        internal static string ReferenceSentToCitavi_Plural {
            get {
                return ResourceManager.GetString("ReferenceSentToCitavi_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Citavi.
        /// </summary>
        internal static string RunCitavi {
            get {
                return ResourceManager.GetString("RunCitavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Citavi.
        /// </summary>
        internal static string ShowKindleQuotation {
            get {
                return ResourceManager.GetString("ShowKindleQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Citavi.
        /// </summary>
        internal static string ShowKindleReference {
            get {
                return ResourceManager.GetString("ShowKindleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show reference.
        /// </summary>
        internal static string ShowReference {
            get {
                return ResourceManager.GetString("ShowReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target project.
        /// </summary>
        internal static string TargetProject {
            get {
                return ResourceManager.GetString("TargetProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current desktop project.
        /// </summary>
        internal static string TargetProject_Desktop {
            get {
                return ResourceManager.GetString("TargetProject_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to Clipboard.
        /// </summary>
        internal static string TextSelectionClipboardSuccess {
            get {
                return ResourceManager.GetString("TextSelectionClipboardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Trace_Comment {
            get {
                return ResourceManager.GetString("Trace_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Trace_Email {
            get {
                return ResourceManager.GetString("Trace_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        internal static string Trace_Name {
            get {
                return ResourceManager.GetString("Trace_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Trace_Send {
            get {
                return ResourceManager.GetString("Trace_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please describe the what you were doing before the error occurred..
        /// </summary>
        internal static string Trace_Text_1 {
            get {
                return ResourceManager.GetString("Trace_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for helping us improve Citavi!&lt;br/&gt;We appreciate your help..
        /// </summary>
        internal static string Trace_Text_2 {
            get {
                return ResourceManager.GetString("Trace_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for PDF….
        /// </summary>
        internal static string TryDownloadPdf {
            get {
                return ResourceManager.GetString("TryDownloadPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
