//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecialChars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecialChars() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.SpecialChars", typeof(SpecialChars).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brackets ähnelt.
        /// </summary>
        public static string Brackets {
            get {
                return ResourceManager.GetString("Brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ellipsis in brackets ähnelt.
        /// </summary>
        public static string BracketsWithEllipsis {
            get {
                return ResourceManager.GetString("BracketsWithEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Character Map ähnelt.
        /// </summary>
        public static string CharMap {
            get {
                return ResourceManager.GetString("CharMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [colon] ähnelt.
        /// </summary>
        public static string ColonReplacement {
            get {
                return ResourceManager.GetString("ColonReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [comma] ähnelt.
        /// </summary>
        public static string CommaReplacement {
            get {
                return ResourceManager.GetString("CommaReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special characters ähnelt.
        /// </summary>
        public static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convert text to Unicode ähnelt.
        /// </summary>
        public static string ConvertTextToUnicodeCharacter {
            get {
                return ResourceManager.GetString("ConvertTextToUnicodeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die En dash ähnelt.
        /// </summary>
        public static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [period] ähnelt.
        /// </summary>
        public static string DotReplacement {
            get {
                return ResourceManager.GetString("DotReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ellipsis ähnelt.
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [none] ähnelt.
        /// </summary>
        public static string EmptyStringReplacement {
            get {
                return ResourceManager.GetString("EmptyStringReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guillemets outward ähnelt.
        /// </summary>
        public static string Guillemets {
            get {
                return ResourceManager.GetString("Guillemets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guillemets inward ähnelt.
        /// </summary>
        public static string GuillemetsGerman {
            get {
                return ResourceManager.GetString("GuillemetsGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single guillemets outward ähnelt.
        /// </summary>
        public static string GuillemetsSingle {
            get {
                return ResourceManager.GetString("GuillemetsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single guillemets inward ähnelt.
        /// </summary>
        public static string GuillemetsSingleGerman {
            get {
                return ResourceManager.GetString("GuillemetsSingleGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One half ähnelt.
        /// </summary>
        public static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lower/upper quotation marks ähnelt.
        /// </summary>
        public static string LowerUpperDoubleQuotationMarks {
            get {
                return ResourceManager.GetString("LowerUpperDoubleQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single lower/upper quotation marks ähnelt.
        /// </summary>
        public static string LowerUpperSingleQuotationMarks {
            get {
                return ResourceManager.GetString("LowerUpperSingleQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non-breaking hyphen ähnelt.
        /// </summary>
        public static string NonBreakingHyphen {
            get {
                return ResourceManager.GetString("NonBreakingHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [non-breaking hyphen] ähnelt.
        /// </summary>
        public static string NonBreakingHyphenReplacement {
            get {
                return ResourceManager.GetString("NonBreakingHyphenReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Non-breaking space ähnelt.
        /// </summary>
        public static string NonBreakingSpace {
            get {
                return ResourceManager.GetString("NonBreakingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [non-breaking space] ähnelt.
        /// </summary>
        public static string NonBreakingSpaceReplacement {
            get {
                return ResourceManager.GetString("NonBreakingSpaceReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [nothing] ähnelt.
        /// </summary>
        public static string NothingReplacement {
            get {
                return ResourceManager.GetString("NothingReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One quarter ähnelt.
        /// </summary>
        public static string OneQuarter {
            get {
                return ResourceManager.GetString("OneQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One third ähnelt.
        /// </summary>
        public static string OneThird {
            get {
                return ResourceManager.GetString("OneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parentheses ähnelt.
        /// </summary>
        public static string Parentheses {
            get {
                return ResourceManager.GetString("Parentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ellipsis in parentheses ähnelt.
        /// </summary>
        public static string ParenthesesWithEllipsis {
            get {
                return ResourceManager.GetString("ParenthesesWithEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [return] ähnelt.
        /// </summary>
        public static string ReturnReplacement {
            get {
                return ResourceManager.GetString("ReturnReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [semicolon] ähnelt.
        /// </summary>
        public static string SemicolonReplacement {
            get {
                return ResourceManager.GetString("SemicolonReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soft hyphen ähnelt.
        /// </summary>
        public static string SoftHyphen {
            get {
                return ResourceManager.GetString("SoftHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [soft return] ähnelt.
        /// </summary>
        public static string SoftReturnReplacement {
            get {
                return ResourceManager.GetString("SoftReturnReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [space] ähnelt.
        /// </summary>
        public static string SpaceReplacement {
            get {
                return ResourceManager.GetString("SpaceReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [tab] ähnelt.
        /// </summary>
        public static string TabReplacement {
            get {
                return ResourceManager.GetString("TabReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quotation marks ähnelt.
        /// </summary>
        public static string UpperQuotes {
            get {
                return ResourceManager.GetString("UpperQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single quotation marks ähnelt.
        /// </summary>
        public static string UpperQuotesSingle {
            get {
                return ResourceManager.GetString("UpperQuotesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zero-width space ähnelt.
        /// </summary>
        public static string ZeroWidthBreakOpportunity {
            get {
                return ResourceManager.GetString("ZeroWidthBreakOpportunity", resourceCulture);
            }
        }
    }
}
