//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeX() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.TeX", typeof(TeX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die col.|cols. ähnelt.
        /// </summary>
        public static string LaTeXNumberingTypeColumn {
            get {
                return ResourceManager.GetString("LaTeXNumberingTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no.|nos. ähnelt.
        /// </summary>
        public static string LaTeXNumberingTypeMargin {
            get {
                return ResourceManager.GetString("LaTeXNumberingTypeMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die p.|pp. ähnelt.
        /// </summary>
        public static string LaTeXNumberingTypePages {
            get {
                return ResourceManager.GetString("LaTeXNumberingTypePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \S|\S\S ähnelt.
        /// </summary>
        public static string LaTeXNumberingTypeParagraph {
            get {
                return ResourceManager.GetString("LaTeXNumberingTypeParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LEd with {0} ähnelt.
        /// </summary>
        public static string LEd_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("LEd_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LEd as footnote with {0} ähnelt.
        /// </summary>
        public static string LEd_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("LEd_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LEd with {0} ähnelt.
        /// </summary>
        public static string LEd_InsertPlaceholder {
            get {
                return ResourceManager.GetString("LEd_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LEd as footnote with {0} ähnelt.
        /// </summary>
        public static string LEd_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("LEd_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LyX with {0} ähnelt.
        /// </summary>
        public static string LyX_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("LyX_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LyX as footnote with {0} ähnelt.
        /// </summary>
        public static string LyX_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("LyX_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LyX with {0} ähnelt.
        /// </summary>
        public static string LyX_InsertPlaceholder {
            get {
                return ResourceManager.GetString("LyX_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in LyX as footnote with {0} ähnelt.
        /// </summary>
        public static string LyX_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("LyX_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in Texmaker with {0} ähnelt.
        /// </summary>
        public static string TeXMaker_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("TeXMaker_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in Texmaker as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXMaker_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("TeXMaker_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in Texmaker with {0} ähnelt.
        /// </summary>
        public static string TeXMaker_InsertPlaceholder {
            get {
                return ResourceManager.GetString("TeXMaker_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in Texmaker as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXMaker_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("TeXMaker_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXnicCenter with {0} ähnelt.
        /// </summary>
        public static string TeXnicCenter_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("TeXnicCenter_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXnicCenter as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXnicCenter_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("TeXnicCenter_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXnicCenter with {0} ähnelt.
        /// </summary>
        public static string TeXnicCenter_InsertPlaceholder {
            get {
                return ResourceManager.GetString("TeXnicCenter_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXnicCenter as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXnicCenter_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("TeXnicCenter_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXstudio with {0} ähnelt.
        /// </summary>
        public static string TeXstudio_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("TeXstudio_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXstudio as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXstudio_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("TeXstudio_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXstudio with {0} ähnelt.
        /// </summary>
        public static string TeXstudio_InsertPlaceholder {
            get {
                return ResourceManager.GetString("TeXstudio_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXstudio as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXstudio_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("TeXstudio_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXworks with {0} ähnelt.
        /// </summary>
        public static string TeXworks_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("TeXworks_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXworks as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXworks_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("TeXworks_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXworks with {0} ähnelt.
        /// </summary>
        public static string TeXworks_InsertPlaceholder {
            get {
                return ResourceManager.GetString("TeXworks_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in TeXworks as footnote with {0} ähnelt.
        /// </summary>
        public static string TeXworks_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("TeXworks_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinEdt with {0} ähnelt.
        /// </summary>
        public static string WinEdt_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("WinEdt_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinEdt as footnote with {0} ähnelt.
        /// </summary>
        public static string WinEdt_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("WinEdt_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinEdt with {0} ähnelt.
        /// </summary>
        public static string WinEdt_InsertPlaceholder {
            get {
                return ResourceManager.GetString("WinEdt_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinEdt as footnote with {0} ähnelt.
        /// </summary>
        public static string WinEdt_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("WinEdt_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinShell with {0} ähnelt.
        /// </summary>
        public static string WinShell_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("WinShell_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinShell as footnote with {0} ähnelt.
        /// </summary>
        public static string WinShell_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("WinShell_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinShell with {0} ähnelt.
        /// </summary>
        public static string WinShell_InsertPlaceholder {
            get {
                return ResourceManager.GetString("WinShell_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinShell as footnote with {0} ähnelt.
        /// </summary>
        public static string WinShell_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("WinShell_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinTeX with {0} ähnelt.
        /// </summary>
        public static string WinTeX_InsertKnowledgeItem {
            get {
                return ResourceManager.GetString("WinTeX_InsertKnowledgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinTeX as footnote with {0} ähnelt.
        /// </summary>
        public static string WinTeX_InsertKnowledgeItemAsFootnote {
            get {
                return ResourceManager.GetString("WinTeX_InsertKnowledgeItemAsFootnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinTeX with {0} ähnelt.
        /// </summary>
        public static string WinTeX_InsertPlaceholder {
            get {
                return ResourceManager.GetString("WinTeX_InsertPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert in WinTeX as footnote with {0} ähnelt.
        /// </summary>
        public static string WinTeX_InsertPlaceholderAsFootnote {
            get {
                return ResourceManager.GetString("WinTeX_InsertPlaceholderAsFootnote", resourceCulture);
            }
        }
    }
}
