//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebLabelsStart {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebLabelsStart() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.WebLabelsStart", typeof(WebLabelsStart).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add-Ins for Microsoft Word and Google Docs ähnelt.
        /// </summary>
        public static string AddIns {
            get {
                return ResourceManager.GetString("AddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add-Ins ähnelt.
        /// </summary>
        public static string AddIns_Criteria {
            get {
                return ResourceManager.GetString("AddIns_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Citavi Picker for {0} lets you add online content to your Citavi projects. ähnelt.
        /// </summary>
        public static string AddIns_Picker_Description {
            get {
                return ResourceManager.GetString("AddIns_Picker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the Picker ähnelt.
        /// </summary>
        public static string AddIns_Picker_Install {
            get {
                return ResourceManager.GetString("AddIns_Picker_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Word Assistant ähnelt.
        /// </summary>
        public static string AddIns_WordAssistant {
            get {
                return ResourceManager.GetString("AddIns_WordAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die With the Citavi Word Assistant, you can insert quotations and citations into your Word document. A bibliography is created automatically in the citation style of your choice. ähnelt.
        /// </summary>
        public static string AddIns_WordAssistant_Description {
            get {
                return ResourceManager.GetString("AddIns_WordAssistant_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the Word Assistant ähnelt.
        /// </summary>
        public static string AddIns_WordAssistant_Install {
            get {
                return ResourceManager.GetString("AddIns_WordAssistant_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically format your citations and bibliography according to the citation style you select. ähnelt.
        /// </summary>
        public static string AddInsDescription {
            get {
                return ResourceManager.GetString("AddInsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die See the manual for more information on installing the add-ins. ähnelt.
        /// </summary>
        public static string AddInsInstallationInstructions {
            get {
                return ResourceManager.GetString("AddInsInstallationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask a question… ähnelt.
        /// </summary>
        public static string AskQuestion {
            get {
                return ResourceManager.GetString("AskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask a question here… ähnelt.
        /// </summary>
        public static string AskQuestionHere {
            get {
                return ResourceManager.GetString("AskQuestionHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purple ähnelt.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi news archive ähnelt.
        /// </summary>
        public static string CitaviNewsArchive {
            get {
                return ResourceManager.GetString("CitaviNewsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi website ähnelt.
        /// </summary>
        public static string CitaviWebsite {
            get {
                return ResourceManager.GetString("CitaviWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining time: {0} seconds ähnelt.
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        public static string CurrentProjects {
            get {
                return ResourceManager.GetString("CurrentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects A-Z ähnelt.
        /// </summary>
        public static string CurrentProjectsAZ {
            get {
                return ResourceManager.GetString("CurrentProjectsAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy policy ähnelt.
        /// </summary>
        public static string DataProtection {
            get {
                return ResourceManager.GetString("DataProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feed and all of its 
        ///messages will be deleted. 
        ///This action cannot be undone. 
        ///Do you want to continue? ähnelt.
        /// </summary>
        public static string DeleteFeed {
            get {
                return ResourceManager.GetString("DeleteFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the project {0} and all its attachments? ähnelt.
        /// </summary>
        public static string DeleteProjectConfirmation {
            get {
                return ResourceManager.GetString("DeleteProjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the project name for confirmation: ähnelt.
        /// </summary>
        public static string DeleteProjectConfirmationProjectName {
            get {
                return ResourceManager.GetString("DeleteProjectConfirmationProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Citavi for Windows ähnelt.
        /// </summary>
        public static string DownloadCitaviForWindows {
            get {
                return ResourceManager.GetString("DownloadCitaviForWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS feed ähnelt.
        /// </summary>
        public static string FeedRSS {
            get {
                return ResourceManager.GetString("FeedRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed will be loaded over https:// ähnelt.
        /// </summary>
        public static string FeedsAreLoadedOverHttps {
            get {
                return ResourceManager.GetString("FeedsAreLoadedOverHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gray ähnelt.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL should begin with &quot;https://&quot; ähnelt.
        /// </summary>
        public static string HttpsUrlRequired {
            get {
                return ResourceManager.GetString("HttpsUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Another reference management program ähnelt.
        /// </summary>
        public static string Import_Others {
            get {
                return ResourceManager.GetString("Import_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which project would you like to import the reference into? ähnelt.
        /// </summary>
        public static string ImportInWhichProject {
            get {
                return ResourceManager.GetString("ImportInWhichProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;Reference imported.&lt;/b&gt;&lt;br /&gt;Click &lt;a&gt;here&lt;/a&gt; to display. ähnelt.
        /// </summary>
        public static string ImportReferencesEnd {
            get {
                return ResourceManager.GetString("ImportReferencesEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The reference is being imported. You will be notified once the import is complete. ähnelt.
        /// </summary>
        public static string ImportReferencesStart {
            get {
                return ResourceManager.GetString("ImportReferencesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install the Picker ähnelt.
        /// </summary>
        public static string InstallPicker {
            get {
                return ResourceManager.GetString("InstallPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid URL ähnelt.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi will use your settings from Citavi for Windows. ähnelt.
        /// </summary>
        public static string IsDesktopDefinition {
            get {
                return ResourceManager.GetString("IsDesktopDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent projects ähnelt.
        /// </summary>
        public static string LastUsedProjects {
            get {
                return ResourceManager.GetString("LastUsedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading… ähnelt.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual ähnelt.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge accounts ähnelt.
        /// </summary>
        public static string MergeAccounts {
            get {
                return ResourceManager.GetString("MergeAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing entry ähnelt.
        /// </summary>
        public static string MissingInput {
            get {
                return ResourceManager.GetString("MissingInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn more ähnelt.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die See the manual for more information. ähnelt.
        /// </summary>
        public static string MoreInfoInManual {
            get {
                return ResourceManager.GetString("MoreInfoInManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projects ähnelt.
        /// </summary>
        public static string NavigationBar_Projects {
            get {
                return ResourceManager.GetString("NavigationBar_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add-Ins and Settings ähnelt.
        /// </summary>
        public static string NavigationBar_Settings {
            get {
                return ResourceManager.GetString("NavigationBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create project ähnelt.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orange ähnelt.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other settings ähnelt.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year derived includes Original publication (for citations) ähnelt.
        /// </summary>
        public static string Others_FirstPublicationYear {
            get {
                return ResourceManager.GetString("Others_FirstPublicationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When this option is selected, Year derived first checks whether a year is present in the Original publication field (of the reference or its parent reference) and uses it if present. ähnelt.
        /// </summary>
        public static string Others_FirstPublicationYear_Description {
            get {
                return ResourceManager.GetString("Others_FirstPublicationYear_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi Picker for your browser ähnelt.
        /// </summary>
        public static string Picker {
            get {
                return ResourceManager.GetString("Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save references and quotations you find online in your project. ähnelt.
        /// </summary>
        public static string PickerDescription {
            get {
                return ResourceManager.GetString("PickerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project could not be created. Please try again. ähnelt.
        /// </summary>
        public static string ProjectCouldNotBeCreated {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;Creating project&lt;/b&gt; ähnelt.
        /// </summary>
        public static string ProjectIsBeingCreated {
            get {
                return ResourceManager.GetString("ProjectIsBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project leader ähnelt.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect project name. ähnelt.
        /// </summary>
        public static string ProjectNameIsWrong {
            get {
                return ResourceManager.GetString("ProjectNameIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project owner ähnelt.
        /// </summary>
        public static string ProjectOwner {
            get {
                return ResourceManager.GetString("ProjectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;b&gt;Project created.&lt;/b&gt;&lt;br/&gt;Click &lt;a&gt;here&lt;/a&gt; to open. ähnelt.
        /// </summary>
        public static string ProjectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show hidden RSS messages ähnelt.
        /// </summary>
        public static string ResetReadNews {
            get {
                return ResourceManager.GetString("ResetReadNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string RSSError {
            get {
                return ResourceManager.GetString("RSSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS feed URL already exists ähnelt.
        /// </summary>
        public static string RSSFeedAlreadyPresent {
            get {
                return ResourceManager.GetString("RSSFeedAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some feeds could not be loaded ähnelt.
        /// </summary>
        public static string RSSFeedLoadError {
            get {
                return ResourceManager.GetString("RSSFeedLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS feeds ähnelt.
        /// </summary>
        public static string RSSFeeds {
            get {
                return ResourceManager.GetString("RSSFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscribe to feed: ähnelt.
        /// </summary>
        public static string RSSFeedUrl {
            get {
                return ResourceManager.GetString("RSSFeedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feed URL ähnelt.
        /// </summary>
        public static string RSSFeedUrlPlaceholder {
            get {
                return ResourceManager.GetString("RSSFeedUrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hidden messages successfully marked as unread. ähnelt.
        /// </summary>
        public static string RSSHiddenNewsVisibleAgain {
            get {
                return ResourceManager.GetString("RSSHiddenNewsVisibleAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS settings ähnelt.
        /// </summary>
        public static string RSSSettings {
            get {
                return ResourceManager.GetString("RSSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show hidden RSS messages ähnelt.
        /// </summary>
        public static string RSSShowHiddenNews {
            get {
                return ResourceManager.GetString("RSSShowHiddenNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My feeds: ähnelt.
        /// </summary>
        public static string RSSSubscribedFeeds {
            get {
                return ResourceManager.GetString("RSSSubscribedFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving… ähnelt.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team options ähnelt.
        /// </summary>
        public static string ShareProject {
            get {
                return ResourceManager.GetString("ShareProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share project ähnelt.
        /// </summary>
        public static string ShareProjectLabel {
            get {
                return ResourceManager.GetString("ShareProjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t show again ähnelt.
        /// </summary>
        public static string ShowNoMore {
            get {
                return ResourceManager.GetString("ShowNoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection ähnelt.
        /// </summary>
        public static string SplitterTrigger_Projects_Left {
            get {
                return ResourceManager.GetString("SplitterTrigger_Projects_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terms of use ähnelt.
        /// </summary>
        public static string TermsOfUsage {
            get {
                return ResourceManager.GetString("TermsOfUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string Tooltip_Import {
            get {
                return ResourceManager.GetString("Tooltip_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        public static string Tooltip_MarkAsRead {
            get {
                return ResourceManager.GetString("Tooltip_MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why? ähnelt.
        /// </summary>
        public static string Why {
            get {
                return ResourceManager.GetString("Why", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Why not? ähnelt.
        /// </summary>
        public static string WhyNot {
            get {
                return ResourceManager.GetString("WhyNot", resourceCulture);
            }
        }
    }
}
