//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebLabelsHelpTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebLabelsHelpTexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.WebLabelsHelpTexts", typeof(WebLabelsHelpTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can merge two accounts or delete your account. ähnelt.
        /// </summary>
        public static string Account_AccountCriteriaAccountManagement {
            get {
                return ResourceManager.GetString("Account_AccountCriteriaAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information for each license key can be found in the right-hand column. Click or tap a link for additional options. ähnelt.
        /// </summary>
        public static string Account_LicensesTitle {
            get {
                return ResourceManager.GetString("Account_LicensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order licenses or request a quote in the Citavi Shop. ähnelt.
        /// </summary>
        public static string Account_NewLicense {
            get {
                return ResourceManager.GetString("Account_NewLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click or tap a blue link to edit your information or change your profile image. ähnelt.
        /// </summary>
        public static string Account_ProfileTitle {
            get {
                return ResourceManager.GetString("Account_ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Criteria header ähnelt.
        /// </summary>
        public static string App_CriteriaHeader {
            get {
                return ResourceManager.GetString("App_CriteriaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More ähnelt.
        /// </summary>
        public static string App_MoreReferenceNavigation {
            get {
                return ResourceManager.GetString("App_MoreReferenceNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book subtitle ähnelt.
        /// </summary>
        public static string App_Subtitle_Book {
            get {
                return ResourceManager.GetString("App_Subtitle_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book title ähnelt.
        /// </summary>
        public static string App_Title_Book {
            get {
                return ResourceManager.GetString("App_Title_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Book title supplement ähnelt.
        /// </summary>
        public static string App_TitleSupplement_Book {
            get {
                return ResourceManager.GetString("App_TitleSupplement_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will be redirected to the cleverbridge website. You can change the license quantity there. ähnelt.
        /// </summary>
        public static string Shop_Buy {
            get {
                return ResourceManager.GetString("Shop_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your order for this session is displayed in the shopping cart. You can change the quantity there. ähnelt.
        /// </summary>
        public static string Shop_Cart {
            get {
                return ResourceManager.GetString("Shop_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can find information on the selected product. ähnelt.
        /// </summary>
        public static string Shop_ProductDetails {
            get {
                return ResourceManager.GetString("Shop_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Here you can find all products that belong to the group you selected in the left-hand column. ähnelt.
        /// </summary>
        public static string Shop_ProductsList {
            get {
                return ResourceManager.GetString("Shop_ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will be redirected to the cleverbridge website for your quote. ähnelt.
        /// </summary>
        public static string Shop_Quote {
            get {
                return ResourceManager.GetString("Shop_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Different categories offer different licenses and pricing. Please select the category that applies to you. ähnelt.
        /// </summary>
        public static string Shop_ShopCriteriaHeader {
            get {
                return ResourceManager.GetString("Shop_ShopCriteriaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project criteria ähnelt.
        /// </summary>
        public static string Start_ProjectCriteria {
            get {
                return ResourceManager.GetString("Start_ProjectCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project list ähnelt.
        /// </summary>
        public static string Start_ProjectsList {
            get {
                return ResourceManager.GetString("Start_ProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS Feeds button ähnelt.
        /// </summary>
        public static string Start_RSSFeedsButton {
            get {
                return ResourceManager.GetString("Start_RSSFeedsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RSS Feed list ähnelt.
        /// </summary>
        public static string Start_RSSFeedsList {
            get {
                return ResourceManager.GetString("Start_RSSFeedsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Start_SettingsMenuLink {
            get {
                return ResourceManager.GetString("Start_SettingsMenuLink", resourceCulture);
            }
        }
    }
}
