//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebLabelsShop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebLabelsShop() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.WebLabelsShop", typeof(WebLabelsShop).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Academic pricing for education, government, and non-profit ähnelt.
        /// </summary>
        public static string AcademicPricingLabel {
            get {
                return ResourceManager.GetString("AcademicPricingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special ähnelt.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special price only valid on ähnelt.
        /// </summary>
        public static string ActionPrice {
            get {
                return ResourceManager.GetString("ActionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This price is only valid for
        ///&lt;ul&gt;
        ///&lt;li&gt;Persons using Citavi exclusively for their own use&lt;/li&gt;
        ///&lt;li&gt;Students&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string ActionPriceDescriptionHtml {
            get {
                return ResourceManager.GetString("ActionPriceDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add licenses ähnelt.
        /// </summary>
        public static string AddLicenses {
            get {
                return ResourceManager.GetString("AddLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The total price is displayed with discounts applied (if any). If sales tax is applicable it will be shown on your invoice.  ähnelt.
        /// </summary>
        public static string AddLicensesDescription {
            get {
                return ResourceManager.GetString("AddLicensesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The total price is displayed. If sales tax is applicable it will be shown on your invoice. ähnelt.
        /// </summary>
        public static string AddLicensesHomeDescription {
            get {
                return ResourceManager.GetString("AddLicensesHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add maintenance (yearly payments) ähnelt.
        /// </summary>
        public static string AddMaintenance {
            get {
                return ResourceManager.GetString("AddMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add additional products ähnelt.
        /// </summary>
        public static string AddProducts {
            get {
                return ResourceManager.GetString("AddProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add to basket ähnelt.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add upgrade ähnelt.
        /// </summary>
        public static string AddUpgrade {
            get {
                return ResourceManager.GetString("AddUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discount for site license users ähnelt.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Business pricing for commercial use ähnelt.
        /// </summary>
        public static string BusinessPricingLabel {
            get {
                return ResourceManager.GetString("BusinessPricingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase ähnelt.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Before purchasing a gift certificate, please make sure that the recipient is not already able to use Citavi for free &lt;a href=&apos;//www.citavi.com/students#license&apos; target=&apos;_blank&apos;&gt;through a site license&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string BuyVoucherDescriptionHtml {
            get {
                return ResourceManager.GetString("BuyVoucherDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subscriptions cannot be combined with product purchases in the same order. Please carry out one purchase at a time or remove the existing item from your basket. ähnelt.
        /// </summary>
        public static string CannotBuy {
            get {
                return ResourceManager.GetString("CannotBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete your order ähnelt.
        /// </summary>
        public static string Cart_CompleteOrder {
            get {
                return ResourceManager.GetString("Cart_CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The subscription is valid until {0}.&lt;br/&gt;The price will be reduced based on the date. ähnelt.
        /// </summary>
        public static string Cart_IntegrateSubscriptionDescription {
            get {
                return ResourceManager.GetString("Cart_IntegrateSubscriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The payment method you used last time will be used again unless you change it. Sie können sie &lt;a id=&quot;subscriptionPaymentMethod&quot;&gt;View or edit payment method&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string Cart_SubscriptionPayment {
            get {
                return ResourceManager.GetString("Cart_SubscriptionPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already have a product in your basket. Subscription-based products can only be ordered along with a new subscription. If you want to extend an existing subscription, please place a second order. ähnelt.
        /// </summary>
        public static string CartHasCommercialProducts {
            get {
                return ResourceManager.GetString("CartHasCommercialProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your basket is empty. Click &quot;Add to basket&quot; to add licenses to the basket. ähnelt.
        /// </summary>
        public static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Want more than {0} licenses? Please contact us: &lt;a href=&quot;mailto:sales@citavi.com&quot;&gt;sales@citavi.com&lt;/a&gt; ähnelt.
        /// </summary>
        public static string CartQuantityIsOverLimit {
            get {
                return ResourceManager.GetString("CartQuantityIsOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your basket has been updated ähnelt.
        /// </summary>
        public static string CartUpdated {
            get {
                return ResourceManager.GetString("CartUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue without logging in ähnelt.
        /// </summary>
        public static string CitaviAccountContinueWithoutLogin {
            get {
                return ResourceManager.GetString("CitaviAccountContinueWithoutLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string CitaviAccountLogin {
            get {
                return ResourceManager.GetString("CitaviAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already have a Citavi account? ähnelt.
        /// </summary>
        public static string CitaviAccountPresent {
            get {
                return ResourceManager.GetString("CitaviAccountPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No account?&lt;br/&gt; Continue without logging in. ähnelt.
        /// </summary>
        public static string CitaviAccountPresentNo {
            get {
                return ResourceManager.GetString("CitaviAccountPresentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please log in&lt;br/&gt;&lt;br/&gt;You may benefit from the following:&lt;br/&gt;&lt;br/&gt;&lt;ul&gt;&lt;li&gt;volume discounts due to previous orders&lt;/li&gt;&lt;li&gt;upgrade discounts&lt;/li&gt;&lt;li&gt;special offers&lt;/li&gt;&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string CitaviAccountPresentYes {
            get {
                return ResourceManager.GetString("CitaviAccountPresentYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi for commercial use ähnelt.
        /// </summary>
        public static string CitaviForCommercialUse {
            get {
                return ResourceManager.GetString("CitaviForCommercialUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi for education, government, and non-profit ähnelt.
        /// </summary>
        public static string CitaviForHighSchools {
            get {
                return ResourceManager.GetString("CitaviForHighSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Citavi for personal and student use ähnelt.
        /// </summary>
        public static string CitaviForStudents {
            get {
                return ResourceManager.GetString("CitaviForStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to open ähnelt.
        /// </summary>
        public static string ClickToOpen {
            get {
                return ResourceManager.GetString("ClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die commercial clients ähnelt.
        /// </summary>
        public static string CommercialClients {
            get {
                return ResourceManager.GetString("CommercialClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compare products ähnelt.
        /// </summary>
        public static string CompareProducts {
            get {
                return ResourceManager.GetString("CompareProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently in your possession ähnelt.
        /// </summary>
        public static string CurrentlyInYourPossession {
            get {
                return ResourceManager.GetString("CurrentlyInYourPossession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discounted prices ähnelt.
        /// </summary>
        public static string DiscountedPrices {
            get {
                return ResourceManager.GetString("DiscountedPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die These prices are only valid for
        ///&lt;ul&gt;
        ///&lt;li&gt;Institutions of higher education&lt;/li&gt;
        ///&lt;li&gt;Schools&lt;/li&gt;
        ///&lt;li&gt;Government agencies&lt;/li&gt;
        ///&lt;li&gt;Non-Governmental Organizations (NGOs)&lt;/li&gt;
        ///&lt;li&gt;Registered non-profit organizations&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string DiscountedPricesDescriptionHtml {
            get {
                return ResourceManager.GetString("DiscountedPricesDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editions ähnelt.
        /// </summary>
        public static string Editions {
            get {
                return ResourceManager.GetString("Editions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eligible upgrade licenses ähnelt.
        /// </summary>
        public static string EligibleLicenses {
            get {
                return ResourceManager.GetString("EligibleLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check out ähnelt.
        /// </summary>
        public static string GoToCashRegister {
            get {
                return ResourceManager.GetString("GoToCashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Universities, government agencies, non-profit organizations, etc. ähnelt.
        /// </summary>
        public static string HighSchoolsAuthoritiesEtc {
            get {
                return ResourceManager.GetString("HighSchoolsAuthoritiesEtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home pricing for personal and student use ähnelt.
        /// </summary>
        public static string HomePricingLabel {
            get {
                return ResourceManager.GetString("HomePricingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add {0} subscription ähnelt.
        /// </summary>
        public static string IntegrateSubscription {
            get {
                return ResourceManager.GetString("IntegrateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add subscription ähnelt.
        /// </summary>
        public static string IntegrationOfSubscription {
            get {
                return ResourceManager.GetString("IntegrationOfSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already purchased ähnelt.
        /// </summary>
        public static string InYourPossession {
            get {
                return ResourceManager.GetString("InYourPossession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses: ähnelt.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:License|Licenses} ähnelt.
        /// </summary>
        public static string Licenses_Smart {
            get {
                return ResourceManager.GetString("Licenses_Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already have a Citavi license?&lt;br/&gt; &lt;a href=&quot;/my-shop#/products/upgrade&quot;&gt;Log in&lt;/a&gt; or &lt;a id=&quot;registerHere&quot;&gt;create an account&lt;/a&gt; to receive upgrade and volume discounts. ähnelt.
        /// </summary>
        public static string LoginToMyShop {
            get {
                return ResourceManager.GetString("LoginToMyShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected licenses are valid indefinitely for the version purchased but upgrades to a new version require an additional purchase.&lt;br/&gt;&lt;br/&gt;&lt;span class=&quot;segoeUiSemibold&quot;&gt;With a maintenance subscription you will receive new upgrades as soon as they are released.&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;If you decide not purchase a maintenance subscription, you can still purchase upgrades individually with a 50% discount off the normal price. ähnelt.
        /// </summary>
        public static string MaintenanceInfo {
            get {
                return ResourceManager.GetString("MaintenanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die months ähnelt.
        /// </summary>
        public static string MonthsLabel {
            get {
                return ResourceManager.GetString("MonthsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtotal ähnelt.
        /// </summary>
        public static string Netto {
            get {
                return ResourceManager.GetString("Netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New subscription ähnelt.
        /// </summary>
        public static string NewSubscription {
            get {
                return ResourceManager.GetString("NewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your account does not contain any licenses that are eligible for an upgrade. ähnelt.
        /// </summary>
        public static string NoUpgradesAvailable {
            get {
                return ResourceManager.GetString("NoUpgradesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Categories ähnelt.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Citavi Account ähnelt.
        /// </summary>
        public static string Order_OpenAccount {
            get {
                return ResourceManager.GetString("Order_OpenAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will receive two emails from our e-commerce provider cleverbridge:&lt;br/&gt;&lt;ul&gt;&lt;li&gt;An email with your receipt&lt;/li&gt;&lt;li&gt;An email with subscription information&lt;/li&gt;&lt;/ul&gt;&lt;br/&gt;&lt;br/&gt;Your order is now available in your Citavi account. ähnelt.
        /// </summary>
        public static string Order_Text {
            get {
                return ResourceManager.GetString("Order_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for your order! ähnelt.
        /// </summary>
        public static string Order_Title {
            get {
                return ResourceManager.GetString("Order_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new licenses have been added to an existing subscription. In the future, you&apos;ll only receive one bill for the renewal of all items in the subscription.&lt;br/&gt;&lt;br/&gt;The price for this order will be calculated based on the time remaining until the subscription renewal. ähnelt.
        /// </summary>
        public static string PartialBillInfo {
            get {
                return ResourceManager.GetString("PartialBillInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Partial bill until {0} ähnelt.
        /// </summary>
        public static string PartialBillLabel {
            get {
                return ResourceManager.GetString("PartialBillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gift certificate ähnelt.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The VAT amount depends on international trade agreements and is displayed on the invoice. In certain cases, there may be no VAT. ähnelt.
        /// </summary>
        public static string PriceCalculationDisclaimer {
            get {
                return ResourceManager.GetString("PriceCalculationDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtotal (without VAT) ähnelt.
        /// </summary>
        public static string PriceNetto {
            get {
                return ResourceManager.GetString("PriceNetto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Products ähnelt.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity ähnelt.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected product has been removed ähnelt.
        /// </summary>
        public static string RemovedFromCart {
            get {
                return ResourceManager.GetString("RemovedFromCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Renewal date ähnelt.
        /// </summary>
        public static string RenewalDate {
            get {
                return ResourceManager.GetString("RenewalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print quote ähnelt.
        /// </summary>
        public static string RequestOffer {
            get {
                return ResourceManager.GetString("RequestOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You already have a product with the same validity period in your basket. In this order you can only add products with the same validity period. To add an additional subscription with a different validity period, place a second order. ähnelt.
        /// </summary>
        public static string SelectAllowedSubscription {
            get {
                return ResourceManager.GetString("SelectAllowedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select subscription ähnelt.
        /// </summary>
        public static string SelectSubscription {
            get {
                return ResourceManager.GetString("SelectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses and other products with the same renewal date are bundled together in a subscription.&lt;br/&gt;&lt;br/&gt;Select the subscription you want to add products to or create a new subscription. ähnelt.
        /// </summary>
        public static string SelectSubscriptionText1 {
            get {
                return ResourceManager.GetString("SelectSubscriptionText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The price for this order will be calculated based on the time remaining until the subscription renewal.&lt;br/&gt;&lt;br/&gt;Upon renewal you&apos;ll pay the full price for the next year. ähnelt.
        /// </summary>
        public static string SelectSubscriptionText2 {
            get {
                return ResourceManager.GetString("SelectSubscriptionText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discount levels ähnelt.
        /// </summary>
        public static string ShowDiscountLevels {
            get {
                return ResourceManager.GetString("ShowDiscountLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special price for former site license users ähnelt.
        /// </summary>
        public static string SpecialDiscountPrice {
            get {
                return ResourceManager.GetString("SpecialDiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After you leave your university (or if the site license is not renewed), you can purchase your own personal, non-expiring license for Citavi for Windows at a 50% discount. This license is only for home or educational use, cannot be given to another person, and cannot be used in commercial, educational, or other organizations, for which you can purchase {0} or a {1}. ähnelt.
        /// </summary>
        public static string SpecialDiscountPriceHtmlDescription {
            get {
                return ResourceManager.GetString("SpecialDiscountPriceHtmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special offers ähnelt.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special price ähnelt.
        /// </summary>
        public static string SpecialPrice {
            get {
                return ResourceManager.GetString("SpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This special price is only valid for
        ///&lt;ul&gt;
        ///&lt;li&gt;Persons using Citavi exclusively for their own use&lt;/li&gt;
        ///&lt;li&gt;Students&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string SpecialPriceDescriptionHtml {
            get {
                return ResourceManager.GetString("SpecialPriceDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special price for site license users ähnelt.
        /// </summary>
        public static string SpecialPriceForCampusLicense {
            get {
                return ResourceManager.GetString("SpecialPriceForCampusLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After you leave your university (or if the site license is not renewed), you can purchase your own personal, non-expiring license for Citavi for Windows at a 50% discount. This discount can only be used once and is not valid for future purchases. The license can be used on all personal devices, but it cannot be shared with or given to another person.  The license is meant exclusively for home or educational use and cannot be used at work. For use in a commercial or non-profit organization, a license for &lt;a  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string SpecialPriceForCampusLicenseDescriptionHtml {
            get {
                return ResourceManager.GetString("SpecialPriceForCampusLicenseDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new subscription ähnelt.
        /// </summary>
        public static string StartNewSubscription {
            get {
                return ResourceManager.GetString("StartNewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Licenses in subscription (valid until {0}) ähnelt.
        /// </summary>
        public static string SubscriptionsCountLabel {
            get {
                return ResourceManager.GetString("SubscriptionsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VAT {0}%: ähnelt.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total price ähnelt.
        /// </summary>
        public static string TotalPriceWithVat {
            get {
                return ResourceManager.GetString("TotalPriceWithVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtotal (excl. VAT) ähnelt.
        /// </summary>
        public static string TotalWithoutTax {
            get {
                return ResourceManager.GetString("TotalWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit price (excl. VAT): ähnelt.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit price {0} (excl. VAT) ähnelt.
        /// </summary>
        public static string UnitPriceDiscount {
            get {
                return ResourceManager.GetString("UnitPriceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlimited ähnelt.
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upgrades ähnelt.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to obtain an upgrade for licenses you purchased in the past?&lt;br/&gt;You can do so in your Citavi account. ähnelt.
        /// </summary>
        public static string UpgradeHtml1 {
            get {
                return ResourceManager.GetString("UpgradeHtml1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already have a Citavi account? ähnelt.
        /// </summary>
        public static string UpgradeHtml2 {
            get {
                return ResourceManager.GetString("UpgradeHtml2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log in here. ähnelt.
        /// </summary>
        public static string UpgradeHtml3 {
            get {
                return ResourceManager.GetString("UpgradeHtml3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t have a Citavi Account yet? ähnelt.
        /// </summary>
        public static string UpgradeHtml4 {
            get {
                return ResourceManager.GetString("UpgradeHtml4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;a id=&quot;registerHere&quot;&gt;Register here&lt;/a&gt; with the email address that you used for your last order. ähnelt.
        /// </summary>
        public static string UpgradeHtml5 {
            get {
                return ResourceManager.GetString("UpgradeHtml5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upgrade offers ähnelt.
        /// </summary>
        public static string UpgradeOffers {
            get {
                return ResourceManager.GetString("UpgradeOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validity ähnelt.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VAT ähnelt.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gift certificate ähnelt.
        /// </summary>
        public static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gift certificates can only be given to
        ///&lt;ul&gt;
        ///&lt;li&gt;Persons using Citavi exclusively for their own use&lt;/li&gt;
        ///&lt;li&gt;Students&lt;/li&gt;
        ///&lt;/ul&gt; ähnelt.
        /// </summary>
        public static string VoucherDescriptionHtml {
            get {
                return ResourceManager.GetString("VoucherDescriptionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die with a {0}% discount ähnelt.
        /// </summary>
        public static string WithDiscount {
            get {
                return ResourceManager.GetString("WithDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can still add other products. ähnelt.
        /// </summary>
        public static string YouCanAddOtherProducts {
            get {
                return ResourceManager.GetString("YouCanAddOtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your shopping basket ähnelt.
        /// </summary>
        public static string YourCart {
            get {
                return ResourceManager.GetString("YourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You save ähnelt.
        /// </summary>
        public static string YouSave {
            get {
                return ResourceManager.GetString("YouSave", resourceCulture);
            }
        }
    }
}
