//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebLabelsCitaviSpace {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebLabelsCitaviSpace() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Resources.WebLabelsCitaviSpace", typeof(WebLabelsCitaviSpace).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 largest attachments in the project.
        /// </summary>
        public static string Attachments_Biggest {
            get {
                return ResourceManager.GetString("Attachments_Biggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string Attachments_In {
            get {
                return ResourceManager.GetString("Attachments_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Attachments_Type {
            get {
                return ResourceManager.GetString("Attachments_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased in addition.
        /// </summary>
        public static string CitaviSpace_Bought {
            get {
                return ResourceManager.GetString("CitaviSpace_Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining space.
        /// </summary>
        public static string CitaviSpace_Free {
            get {
                return ResourceManager.GetString("CitaviSpace_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included in your license.
        /// </summary>
        public static string CitaviSpace_InLicense {
            get {
                return ResourceManager.GetString("CitaviSpace_InLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string CitaviSpace_Used {
            get {
                return ResourceManager.GetString("CitaviSpace_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used space.
        /// </summary>
        public static string CitaviSpace_UsedSpace {
            get {
                return ResourceManager.GetString("CitaviSpace_UsedSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects and attachments.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
    }
}
