//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwissAcademic.Crm.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwissAcademic.Crm.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AF;sea
        ///AX;euw
        ///AL;euw
        ///DZ;euw
        ///AS;usc
        ///AD;euw
        ///AO;euw
        ///AI;usc
        ///AQ;usc
        ///AG;usc
        ///AR;usc
        ///AM;euw
        ///AW;usc
        ///AU;sea
        ///AT;euw
        ///AZ;euw
        ///BS;usc
        ///BH;euw
        ///BD;sea
        ///BB;usc
        ///BY;euw
        ///BE;euw
        ///BZ;usc
        ///BJ;euw
        ///BM;usc
        ///BT;sea
        ///BO;usc
        ///BQ;usc
        ///BA;euw
        ///BW;euw
        ///BV;euw
        ///BR;usc
        ///IO;sea
        ///BN;sea
        ///BG;euw
        ///BF;euw
        ///BI;euw
        ///KH;sea
        ///CM;euw
        ///CA;usc
        ///CV;euw
        ///KY;usc
        ///CF;euw
        ///TD;euw
        ///CL;usc
        ///CN;sea
        ///CX;sea
        ///CC;sea
        ///CO;usc
        ///KM;euw
        ///CG;euw
        ///CD;euw
        ///CK;sea
        ///CR;usc
        ///CI;euw
        ///HR;euw
        ///CU;usc
        ///CW;usc
        ///CY;euw
        ///CZ;euw
        ///DK;euw
        ///DJ;euw
        ///DM;usc
        ///DO;usc
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AzureRegions {
            get {
                return ResourceManager.GetString("AzureRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ##addOn
        ///
        ///##regards_firstline
        ///
        ///##regards_secondline
        ///
        ///-----
        ///
        ///##disclaimer
        ///
        ///##address
        ///
        ///https://www.citavi.com ähnelt.
        /// </summary>
        internal static string BulkEmailPlainTextTemplate {
            get {
                return ResourceManager.GetString("BulkEmailPlainTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///        @media screen {
        ///            @font-face {
        ///                font-family: &apos;Open Sans&apos;;
        ///                font-style: normal;
        ///                font-weight: 300;
        ///                src: local(&apos;Open [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BulkEmailTemplate {
            get {
                return ResourceManager.GetString("BulkEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die automatische Prüfung der cleverbridge APIs (alle 15 Minuten) hat einen Fehler gefunden. Folgender API-Aufruf war erfolglos:
        ///
        ///$ERROR$
        ///
        ///Der Citavi-Shop wird ggf. nicht korrekt angezeigt oder funktioniert gar nicht.
        ///
        ///Bitte selbst prüfen, ob der Fehler noch besteht, indem man den Link in den Browser eingibt. 
        ///
        ///Der Fehler besteht nicht mehr, wenn dieser String angezeigt wird (keine genaue Überprüfung erforderlich): [{&quot;client_id&quot;:&quot;635&quot;,&quot;product_id&quot;:&quot;150710&quot;,&quot;locale&quot;:&quot;de&quot;,&quot;currency&quot;:{&quot;symbol&quot;:&quot;CHF&quot;,&quot;is [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CleverbridgeErrorMail {
            get {
                return ResourceManager.GetString("CleverbridgeErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Bestellung mit der cleverbridge-Referenznummer $CBORDERNUMMER$ konnte vom CRM aufgrund eines Fehlers nicht verarbeitet werden.
        ///
        ///$ERROR$
        ///
        ///Diese Nachricht bitte an Marc weiterleiten, damit er den Vorgang prüfen kann.
        ///
        ///Marc informiert nach der Prüfung, wie mit der Bestellung weiter verfahren werden soll. ähnelt.
        /// </summary>
        internal static string CleverbridgeOrderFailedErrorMail {
            get {
                return ResourceManager.GetString("CleverbridgeOrderFailedErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///        @media screen {
        ///            @font-face {
        ///                font-family: &apos;Open Sans&apos;;
        ///                font-style: normal;
        ///                font-weight: 300;
        ///                src: local(&apos;Open [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmailBibliographyTemplate {
            get {
                return ResourceManager.GetString("EmailBibliographyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///        @media screen {
        ///            @font-face {
        ///                font-family: &apos;Open Sans&apos;;
        ///                font-style: normal;
        ///                font-weight: 300;
        ///                src: local(&apos;Open [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmailButtonTemplate {
            get {
                return ResourceManager.GetString("EmailButtonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ##subject
        ///
        ///-----
        ///
        ///##first_paragraph
        ///
        ///##second_paragraph
        ///
        ///##button:
        ///id_link
        ///
        ///##last_paragraph
        ///
        ///##regards_firstline
        ///
        ///##regards_secondline
        ///
        ///-----
        ///
        ///##disclaimer
        ///
        ///##address
        ///
        ///https://www.citavi.com ähnelt.
        /// </summary>
        internal static string EmailPlainTextTemplate {
            get {
                return ResourceManager.GetString("EmailPlainTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        /* FONTS */
        ///        @media screen {
        ///            @font-face {
        ///                font-family: &apos;Open Sans&apos;;
        ///                font-style: normal;
        ///                font-weight: 300;
        ///                src: local(&apos;Open [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmailWithoutButtonTemplate {
            get {
                return ResourceManager.GetString("EmailWithoutButtonTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] vouchers_gift_de {
            get {
                object obj = ResourceManager.GetObject("vouchers_gift_de", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] vouchers_gift_en {
            get {
                object obj = ResourceManager.GetObject("vouchers_gift_en", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
